using DataDeveloper.Data.Interfaces;
using DataDeveloper.Data.Models;
using DataDeveloper.Data.Models.FileImport;
using DataDeveloper.Data.Models.TableDesigner;
using DataDeveloper.Data.Services.TableDesigner;

namespace DataDeveloper.Data.Services.FileImport;

/// <summary>
/// Executes a file import: optionally creates the destination table, then streams rows from the
/// file and inserts them via <see cref="EditableResultSetCommandBuilder.BuildInsert"/> (which
/// already handles per-provider identifier quoting and parameter formatting).
/// </summary>
public static class FileImportEngine
{
    private const int BatchSize = 500;

    public static async Task CreateTableAsync(
        IConnectionSettings connectionSettings,
        TableDefinition tableDefinition,
        CancellationToken cancellationToken = default)
    {
        var script = TableDdlScriptBuilder.BuildCreateTableScript(connectionSettings.DatabaseType, tableDefinition);
        var executor = connectionSettings.GetStatementExecutor();
        await executor.ExecuteStatement(script, cancellationToken: cancellationToken);
    }

    public static List<ColumnModel> BuildColumnModels(TableDefinition tableDefinition)
    {
        var primaryKeyColumns = tableDefinition.PrimaryKey.ColumnNames.ToHashSet(StringComparer.OrdinalIgnoreCase);

        return tableDefinition.Columns.Select(column => new ColumnModel
        {
            Name = column.Name,
            DataType = column.DataType,
            Length = column.Length ?? 0,
            Precision = column.Precision ?? 0,
            Scale = column.Scale ?? 0,
            IsNullable = column.IsNullable,
            IsPrimaryKey = primaryKeyColumns.Contains(column.Name),
            IsAutoGenerated = column.IsIdentity,
            HasDefaultValue = !string.IsNullOrWhiteSpace(column.DefaultValue)
        }).ToList();
    }

    public static async Task<FileImportResult> ImportRowsAsync(
        IConnectionSettings connectionSettings,
        string tableName,
        IReadOnlyList<ColumnModel> tableColumns,
        string filePath,
        IReadOnlyList<FileImportColumnMapping> mappings,
        IProgress<(int Completed, int Total)>? progress = null,
        CancellationToken cancellationToken = default)
    {
        var includedMappings = mappings.Where(mapping => mapping.IsIncluded).ToList();
        var headers = includedMappings
            .Select(mapping => mapping.NewColumn?.Name ?? mapping.TargetColumnName ?? string.Empty)
            .ToList();

        var totalRows = FileImportReader.ReadAllRows(filePath).Count();

        var executor = connectionSettings.GetStatementExecutor();
        var databaseType = connectionSettings.DatabaseType;
        var errors = new List<string>();
        var importedCount = 0;
        var failedCount = 0;
        var batchImportedCount = 0;
        var rowIndex = 0;

        await executor.BeginTransaction(cancellationToken);
        try
        {
            foreach (var row in FileImportReader.ReadAllRows(filePath))
            {
                cancellationToken.ThrowIfCancellationRequested();
                rowIndex++;

                var values = includedMappings
                    .Select(mapping => NormalizeValue(mapping.SourceColumnIndex < row.Length ? row[mapping.SourceColumnIndex] : null))
                    .ToList();

                var command = EditableResultSetCommandBuilder.BuildInsert(databaseType, tableName, headers, tableColumns, values);
                if (command is null)
                {
                    failedCount++;
                    errors.Add($"Row {rowIndex}: could not build an insert statement for this row.");
                    continue;
                }

                try
                {
                    await executor.ExecuteCommandInTransaction(command, cancellationToken: cancellationToken);
                    batchImportedCount++;
                }
                catch (Exception ex) when (ex is not OperationCanceledException)
                {
                    // A failed statement leaves the transaction unusable on some providers
                    // (PostgreSQL aborts the whole transaction until it is rolled back), so the
                    // in-flight batch is rolled back and a fresh transaction started before
                    // continuing to the next row.
                    await executor.RollbackTransaction(CancellationToken.None);
                    batchImportedCount = 0;
                    failedCount++;
                    errors.Add($"Row {rowIndex}: {ex.Message}");
                    await executor.BeginTransaction(cancellationToken);
                    continue;
                }

                if (batchImportedCount >= BatchSize)
                {
                    await executor.CommitTransaction(cancellationToken);
                    importedCount += batchImportedCount;
                    batchImportedCount = 0;
                    await executor.BeginTransaction(cancellationToken);
                }

                progress?.Report((rowIndex, totalRows));
            }

            await executor.CommitTransaction(cancellationToken);
            importedCount += batchImportedCount;
        }
        catch (OperationCanceledException)
        {
            await executor.RollbackTransaction(CancellationToken.None);
            throw;
        }

        return new FileImportResult
        {
            RowsImported = importedCount,
            RowsFailed = failedCount,
            Errors = errors
        };
    }

    /// <summary>
    /// Treats a blank cell or the literal text "NULL" (case-insensitive) — both common null
    /// markers produced by spreadsheet/CSV exports — as an actual database NULL, rather than
    /// sending that text verbatim as a column value (which providers reject outright for
    /// non-text columns, e.g. MySQL's "Incorrect datetime value: 'NULL'").
    /// </summary>
    private static object? NormalizeValue(object? value)
    {
        if (value is not string text)
            return value;

        return string.IsNullOrWhiteSpace(text) || string.Equals(text, "NULL", StringComparison.OrdinalIgnoreCase)
            ? null
            : value;
    }
}
