using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using DataDeveloper.Data.Enums;
using DataDeveloper.Data.Models;
using DataDeveloper.Data.Providers.MySql;
using DataDeveloper.Data.Providers.Oracle;
using DataDeveloper.Data.Providers.PostgresSql;
using DataDeveloper.Data.Providers.SqLite;
using DataDeveloper.Data.Providers.SqlServer;
using DataDeveloper.Interfaces;

namespace DataDeveloper.Services;

public class ConnectionImportService : IConnectionImportService
{
    private readonly IConnectionSettingsRepository _connectionSettingsRepository;

    public ConnectionImportService(IConnectionSettingsRepository connectionSettingsRepository)
    {
        _connectionSettingsRepository = connectionSettingsRepository;
    }

    public async Task<int> ImportAsync(string filePath)
    {
        var json = await File.ReadAllTextAsync(filePath);

        ConnectionExportFile? exportFile;
        try
        {
            exportFile = JsonSerializer.Deserialize<ConnectionExportFile>(json);
        }
        catch (JsonException ex)
        {
            throw new InvalidOperationException("This file is not valid JSON.", ex);
        }

        if (exportFile is null ||
            !string.Equals(exportFile.ExportedBy, ConnectionExportFile.ExpectedExportedBy, StringComparison.Ordinal))
        {
            throw new InvalidOperationException("This file was not generated by Data Developer's connection export.");
        }

        // Older format versions are still readable (this app defines what each version
        // means); only reject files written by a newer, not-yet-understood format.
        if (exportFile.FormatVersion > ConnectionExportFile.CurrentFormatVersion)
        {
            throw new InvalidOperationException("This file was exported by a newer version of Data Developer and can't be imported here.");
        }

        var existingNames = new HashSet<string>(
            _connectionSettingsRepository.LoadAll().Select(connection => connection.Name),
            StringComparer.OrdinalIgnoreCase);

        var importedCount = 0;
        foreach (var entry in exportFile.Connections)
        {
            if (!Enum.TryParse<DatabaseType>(entry.DatabaseType, out var databaseType))
                continue;

            var name = ResolveUniqueName(entry.Name, existingNames);
            existingNames.Add(name);

            // Groups are personal, local organization; imported connections always
            // land ungrouped, even if they came from a grouped export.
            var connection = CreateConnectionSettings(databaseType, entry, name);
            _connectionSettingsRepository.Save(connection);
            importedCount++;
        }

        return importedCount;
    }

    private static string ResolveUniqueName(string baseName, HashSet<string> existingNames)
    {
        if (!existingNames.Contains(baseName))
            return baseName;

        var suffix = 2;
        string candidate;
        do
        {
            candidate = $"{baseName} ({suffix})";
            suffix++;
        } while (existingNames.Contains(candidate));

        return candidate;
    }

    private static ConnectionSettings CreateConnectionSettings(
        DatabaseType databaseType,
        ConnectionExportEntry entry,
        string name)
    {
        ConnectionSettings connection = databaseType switch
        {
            DatabaseType.SqlServer => new SqlServerConnectionSettings
            {
                Server = entry.Server ?? string.Empty,
                Database = entry.Database ?? string.Empty,
                Port = entry.Port ?? 1433,
                AuthenticationMode = Enum.TryParse<SqlServerAuthenticationMode>(entry.SqlServerAuthenticationMode, out var authMode)
                    ? authMode
                    : SqlServerAuthenticationMode.SqlLogin
            },
            DatabaseType.Oracle => new OracleConnectionSettings
            {
                Server = entry.Server ?? string.Empty,
                Database = entry.Database ?? string.Empty,
                Port = entry.Port ?? 1521
            },
            DatabaseType.PostgresSql => new PostgresConnectionSettings
            {
                Server = entry.Server ?? string.Empty,
                Database = entry.Database ?? string.Empty,
                Port = entry.Port ?? 5432
            },
            DatabaseType.MySql => new MySqlConnectionSettings
            {
                Server = entry.Server ?? string.Empty,
                Database = entry.Database ?? string.Empty,
                Port = (uint)(entry.Port ?? 3306)
            },
            DatabaseType.SqLite => new SqLiteConnectionSettings
            {
                Database = entry.Database ?? string.Empty
            },
            _ => throw new NotSupportedException($"Database type {databaseType} is not supported.")
        };

        connection.Id = Guid.NewGuid();
        connection.Name = name;
        connection.DatabaseType = databaseType;
        connection.User = entry.User;
        connection.Encrypt = entry.Encrypt;
        connection.TrustServerCertificate = entry.TrustServerCertificate;
        connection.DmlTransactionMode = Enum.TryParse<DmlTransactionMode>(entry.DmlTransactionMode, out var dmlMode)
            ? dmlMode
            : ConnectionSettings.GetDefaultDmlTransactionMode(databaseType);
        connection.StatementTimeoutSeconds = entry.StatementTimeoutSeconds > 0
            ? entry.StatementTimeoutSeconds
            : ConnectionSettings.DefaultStatementTimeoutSeconds;

        if (!string.IsNullOrEmpty(entry.Password))
            connection.Password = entry.Password;

        return connection;
    }
}
