namespace DataDeveloper.Data.Models;

public class ColumnModel
{
    public string Name { get; set; } = string.Empty;
    public string DataType { get; set; } = string.Empty;
    public int Length { get; set; }
    public int Precision { get; set; }
    public int Scale { get; set; }
    public bool IsNullable { get; set; }
    public bool IsPrimaryKey { get; set; }
    public bool IsAutoGenerated { get; set; }
    public bool HasDefaultValue { get; set; }
}
