<Project>
  <PropertyGroup>
    <VersionPrefix Condition="'$(VersionPrefix)' == ''">$([System.DateTime]::UtcNow.ToString(yy)).$([System.DateTime]::UtcNow.ToString(MMdd)).0</VersionPrefix>
    <VersionSuffix Condition="'$(VersionSuffix)' == ''"></VersionSuffix>
    <Version Condition="'$(Version)' == '' and '$(VersionSuffix)' == ''">$(VersionPrefix)</Version>
    <Version Condition="'$(Version)' == '' and '$(VersionSuffix)' != ''">$(VersionPrefix)-$(VersionSuffix)</Version>
    <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(VersionPrefix)</AssemblyVersion>
    <FileVersion Condition="'$(FileVersion)' == ''">$(VersionPrefix)</FileVersion>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>
  </PropertyGroup>
</Project>
