connect datadeveloper/datadeveloper@FREEPDB1

create table customers
(
    customer_id number generated by default on null as identity primary key,
    name varchar2(100) not null,
    email varchar2(150),
    created_at timestamp default current_timestamp not null
);

create table orders
(
    order_id number generated by default on null as identity primary key,
    customer_id number not null,
    order_total number(10,2) not null,
    status varchar2(30) default 'OPEN' not null,
    created_at timestamp default current_timestamp not null,
    constraint fk_orders_customers foreign key (customer_id) references customers(customer_id)
);

insert into customers (name, email)
values ('Alice Johnson', 'alice@example.com');

insert into customers (name, email)
values ('Bob Smith', 'bob@example.com');

insert into orders (customer_id, order_total, status)
values (1, 149.90, 'OPEN');

insert into orders (customer_id, order_total, status)
values (2, 79.50, 'SHIPPED');

commit;

create or replace view open_orders as
select
    o.order_id,
    c.name as customer_name,
    o.order_total,
    o.status,
    o.created_at
from orders o
join customers c on c.customer_id = o.customer_id
where o.status = 'OPEN';
/

create or replace procedure mark_order_shipped
(
    p_order_id in number
)
as
begin
    update datadeveloper.orders
    set status = 'SHIPPED'
    where order_id = p_order_id;
end;
/

create or replace function get_customer_total
(
    p_customer_id in number
)
return number
as
    v_total number(10, 2);
begin
    select coalesce(sum(order_total), 0)
    into v_total
    from datadeveloper.orders
    where customer_id = p_customer_id;

    return v_total;
end;
/
