using DataDeveloper.Data.Models.TableDesigner;
using DataDeveloper.Data.Services.FileImport;
using Xunit;

namespace DataDeveloper.Tests.FileImport;

public class FileImportEngineTests
{
    [Fact]
    public void BuildColumnModels_MapsColumnFacetsAndFlagsFromTableDefinition()
    {
        var table = new TableDefinition
        {
            SchemaName = string.Empty,
            TableName = "customers"
        };
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "id",
            DataType = "integer",
            IsNullable = false,
            IsIdentity = true
        });
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "name",
            DataType = "nvarchar",
            Length = 200,
            IsNullable = false
        });
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "created_at",
            DataType = "datetime2",
            IsNullable = true,
            DefaultValue = "current_timestamp"
        });
        table.PrimaryKey.ColumnNames.Add("id");

        var columnModels = FileImportEngine.BuildColumnModels(table);

        Assert.Equal(3, columnModels.Count);

        var idColumn = Assert.Single(columnModels, column => column.Name == "id");
        Assert.True(idColumn.IsPrimaryKey);
        Assert.True(idColumn.IsAutoGenerated);
        Assert.False(idColumn.IsNullable);

        var nameColumn = Assert.Single(columnModels, column => column.Name == "name");
        Assert.False(nameColumn.IsPrimaryKey);
        Assert.Equal(200, nameColumn.Length);

        var createdAtColumn = Assert.Single(columnModels, column => column.Name == "created_at");
        Assert.True(createdAtColumn.IsNullable);
        Assert.True(createdAtColumn.HasDefaultValue);
        Assert.False(createdAtColumn.IsAutoGenerated);
    }

    [Fact]
    public void BuildColumnModels_WithNoPrimaryKey_MarksAllColumnsAsNonPrimaryKey()
    {
        var table = new TableDefinition { TableName = "logs" };
        table.Columns.Add(new TableColumnDefinition { Name = "message", DataType = "text" });

        var columnModels = FileImportEngine.BuildColumnModels(table);

        Assert.All(columnModels, column => Assert.False(column.IsPrimaryKey));
    }
}
