using System.Data.Common;
using System.Text;
using DataDeveloper.Data.Services;
using Oracle.ManagedDataAccess.Client;

namespace DataDeveloper.Data.Providers.Oracle;

public class OracleDatabaseProvider : DatabaseProviderBase<OracleConnectionSettings>
{
    public OracleDatabaseProvider(OracleConnectionSettings connectionSettings)
        : base(connectionSettings)
    {
    }

    public override DbConnection GetConnection()
    {
        var connectionStringBuilder = new OracleConnectionStringBuilder
        {
            UserID = ConnectionSettings.User,
            Password = ConnectionSettings.Password,
            DataSource = $"{ConnectionSettings.Server}:{ConnectionSettings.Port}/{ConnectionSettings.Database}"
        };

        return new OracleConnection(connectionStringBuilder.ConnectionString);
    }

    public override string GetTableStatement()
    {
        return """
               select table_name as Name
               from user_tables
               order by table_name
               """;
    }

    public override string GetViewStatement()
    {
        return """
               select view_name as Name
               from user_views
               order by view_name
               """;
    }

    public override string GetColumnStatement()
    {
        var sb = new StringBuilder();

        sb.AppendLine("select");
        sb.AppendLine("    c.column_name as Name,");
        sb.AppendLine("    lower(c.data_type) as DataType,");
        sb.AppendLine("    case");
        sb.AppendLine("        when c.char_col_decl_length is not null then c.char_col_decl_length");
        sb.AppendLine("        when c.data_length is not null then c.data_length");
        sb.AppendLine("        else 0");
        sb.AppendLine("    end as Length,");
        sb.AppendLine("    coalesce(c.data_precision, 0) as Precision,");
        sb.AppendLine("    coalesce(c.data_scale, 0) as Scale,");
        sb.AppendLine("    case when c.nullable = 'Y' then 1 else 0 end as IsNullable,");
        sb.AppendLine("    case when pk.column_name is not null then 1 else 0 end as IsPrimaryKey,");
        sb.AppendLine("    case when c.identity_column = 'YES' then 1 else 0 end as IsAutoGenerated,");
        sb.AppendLine("    case when c.data_default is not null then 1 else 0 end as HasDefaultValue");
        sb.AppendLine("from user_tab_columns c");
        sb.AppendLine("left join (");
        sb.AppendLine("    select ucc.table_name, ucc.column_name");
        sb.AppendLine("    from user_constraints uc");
        sb.AppendLine("    join user_cons_columns ucc on ucc.constraint_name = uc.constraint_name");
        sb.AppendLine("    where uc.constraint_type = 'P'");
        sb.AppendLine(") pk on pk.table_name = c.table_name and pk.column_name = c.column_name");
        sb.AppendLine("where c.table_name = upper(:TableName)");
        sb.AppendLine("order by c.column_id");

        return sb.ToString();
    }

    public override string GetProcedureStatement()
    {
        return """
               select object_name as Name,
                      object_name as SpecificName
               from user_objects
               where object_type = 'PROCEDURE'
               order by object_name
               """;
    }

    public override string GetFunctionStatement()
    {
        return """
               select object_name as Name,
                      object_name as SpecificName,
                      null as DataType
               from user_objects
               where object_type = 'FUNCTION'
               order by object_name
               """;
    }

    public override string GetRoutineParameterStatement()
    {
        return """
               select
                   ':' || lower(argument_name) as "Name",
                   lower(data_type) as "DataType",
                   coalesce(char_length, data_length, 0) as "Length",
                   coalesce(data_precision, 0) as "Precision",
                   coalesce(data_scale, 0) as "Scale",
                   cast(1 as number(1)) as "IsNullable",
                   in_out as "Mode",
                   position as "Position"
               from user_arguments
               where object_name = upper(:SpecificName)
                 and package_name is null
                 and argument_name is not null
                 and data_level = 0
               order by sequence
               """;
    }

    public override string GetColumnDefaultValueStatement()
    {
        // Note: data_default is a LONG column; Oracle's managed provider reads it as the
        // first/only LONG-typed column in the result set, which is sufficient for typical
        // default expressions but may truncate unusually large ones (accepted limitation).
        return """
               select
                   column_name as "ColumnName",
                   data_default as "DefaultValueExpression"
               from user_tab_columns
               where table_name = upper(:TableName)
               order by column_id
               """;
    }

    public override string GetPrimaryKeyStatement()
    {
        return """
               select
                   uc.constraint_name as "ConstraintName",
                   ucc.column_name as "ColumnName",
                   ucc.position as "OrdinalPosition"
               from user_constraints uc
               join user_cons_columns ucc on ucc.constraint_name = uc.constraint_name
               where uc.table_name = upper(:TableName)
                 and uc.constraint_type = 'P'
               order by ucc.position
               """;
    }

    public override string GetForeignKeyStatement()
    {
        return """
               select
                   uc.constraint_name as "ConstraintName",
                   ucc.column_name as "ColumnName",
                   ucc.position as "OrdinalPosition",
                   ruc.owner as "ReferencedSchemaName",
                   ruc.table_name as "ReferencedTableName",
                   rucc.column_name as "ReferencedColumnName",
                   case uc.delete_rule
                       when 'CASCADE' then 'cascade'
                       when 'SET NULL' then 'set null'
                       else '' end as "OnDeleteAction",
                   '' as "OnUpdateAction"
               from user_constraints uc
               join user_cons_columns ucc on ucc.constraint_name = uc.constraint_name
               join user_constraints ruc on ruc.constraint_name = uc.r_constraint_name
               join user_cons_columns rucc on rucc.constraint_name = ruc.constraint_name and rucc.position = ucc.position
               where uc.table_name = upper(:TableName)
                 and uc.constraint_type = 'R'
               order by uc.constraint_name, ucc.position
               """;
    }

    public override string GetIndexStatement()
    {
        return """
               select
                   ui.index_name as "IndexName",
                   case when ui.uniqueness = 'UNIQUE' then 1 else 0 end as "IsUnique",
                   uic.column_name as "ColumnName",
                   case when uic.descend = 'DESC' then 1 else 0 end as "IsDescending",
                   uic.column_position as "OrdinalPosition"
               from user_indexes ui
               join user_ind_columns uic on uic.index_name = ui.index_name
               where ui.table_name = upper(:TableName)
                 and not exists (
                     select 1 from user_constraints uc
                     where uc.table_name = ui.table_name
                       and uc.constraint_type = 'P'
                       and uc.index_name = ui.index_name
                 )
               order by ui.index_name, uic.column_position
               """;
    }
}
