using System.Data.Common;
using System.Text;
using DataDeveloper.Data.Services;
using Microsoft.Data.Sqlite;

namespace DataDeveloper.Data.Providers.SqLite;

public class SqLiteDatabaseProvider : DatabaseProviderBase<SqLiteConnectionSettings>
{
    public SqLiteDatabaseProvider(SqLiteConnectionSettings connectionSettings)
        : base(connectionSettings)
    {
    }

    public override DbConnection GetConnection()
    {
        var connectionStringBuilder = new SqliteConnectionStringBuilder
        {
            DataSource = ConnectionSettings.Database
        };

        return new SqliteConnection(connectionStringBuilder.ConnectionString);
    }

    public override string GetTableStatement()
    {
        return """
               select name as Name
               from sqlite_master
               where type = 'table'
                 and name not like 'sqlite_%'
               order by name
               """;
    }

    public override string GetViewStatement()
    {
        return """
               select name as Name
               from sqlite_master
               where type = 'view'
               order by name
               """;
    }

    public override string GetColumnStatement()
    {
        var sb = new StringBuilder();

        sb.AppendLine("select");
        sb.AppendLine("    p.name as Name,");
        sb.AppendLine("    lower(p.type) as DataType,");
        sb.AppendLine("    0 as Length,");
        sb.AppendLine("    0 as Precision,");
        sb.AppendLine("    0 as Scale,");
        sb.AppendLine("    case when p.\"notnull\" = 0 then 1 else 0 end as IsNullable,");
        sb.AppendLine("    case when p.pk > 0 then 1 else 0 end as IsPrimaryKey,");
        sb.AppendLine("    case when p.pk > 0 and upper(coalesce(p.type, '')) = 'INTEGER' then 1 else 0 end as IsAutoGenerated,");
        sb.AppendLine("    case when p.dflt_value is not null then 1 else 0 end as HasDefaultValue");
        sb.AppendLine("from pragma_table_info(__table_name__) p");
        sb.AppendLine("order by p.cid");

        return sb.ToString();
    }

    public override string GetProcedureStatement()
    {
        return """
               select null as Name, null as SpecificName
               where 1 = 0
               """;
    }

    public override string GetFunctionStatement()
    {
        return """
               select null as Name, null as SpecificName, null as DataType
               where 1 = 0
               """;
    }

    public override string GetRoutineParameterStatement()
    {
        return """
               select null as Name, null as DataType, 0 as Length, 0 as Precision, 0 as Scale, 1 as IsNullable, null as Mode, 0 as Position
               where 1 = 0
               """;
    }

    public override string GetColumnDefaultValueStatement()
    {
        return """
               select
                   p.name as ColumnName,
                   p.dflt_value as DefaultValueExpression
               from pragma_table_info(__table_name__) p
               order by p.cid
               """;
    }

    public override string GetPrimaryKeyStatement()
    {
        // SQLite has no named PK constraint.
        return """
               select
                   '' as ConstraintName,
                   p.name as ColumnName,
                   p.pk as OrdinalPosition
               from pragma_table_info(__table_name__) p
               where p.pk > 0
               order by p.pk
               """;
    }

    public override string GetForeignKeyStatement()
    {
        // SQLite has no named FK constraint; synthesize a stable name from the FK group id
        // so multiple columns of the same foreign key are grouped consistently by the loader.
        return """
               select
                   'fk_' || fk.id as ConstraintName,
                   fk."from" as ColumnName,
                   fk.seq as OrdinalPosition,
                   '' as ReferencedSchemaName,
                   fk."table" as ReferencedTableName,
                   fk."to" as ReferencedColumnName,
                   lower(fk.on_delete) as OnDeleteAction,
                   lower(fk.on_update) as OnUpdateAction
               from pragma_foreign_key_list(__table_name__) fk
               order by fk.id, fk.seq
               """;
    }

    public override string GetIndexStatement()
    {
        return """
               select
                   il.name as IndexName,
                   il."unique" as IsUnique,
                   ix.name as ColumnName,
                   ix.desc as IsDescending,
                   ix.seqno as OrdinalPosition
               from pragma_index_list(__table_name__) il
               join pragma_index_xinfo(il.name) ix on ix.key = 1
               where il.origin = 'c'
               order by il.name, ix.seqno
               """;
    }
}
