using System.Data;
using System.Data.Common;
using System.Text;
using DataDeveloper.Data.Interfaces;
using DataDeveloper.Data.Services;
using Microsoft.Data.SqlClient;

namespace DataDeveloper.Data.Providers.SqlServer;

public class SqlServerDatabaseProvider : DatabaseProviderBase<SqlServerConnectionSettings>
{
    public SqlServerDatabaseProvider(SqlServerConnectionSettings connectionSettings) 
        : base(connectionSettings)
    {
    }

    public override DbConnection GetConnection()
    {
        return new SqlConnection(BuildConnectionString(ConnectionSettings.Database));
    }

    public override IReadOnlyList<string> GetAvailableDatabaseNames()
    {
        using var connection = new SqlConnection(BuildConnectionString("master"));
        connection.Open();
        using var command = connection.CreateCommand();
        command.CommandText = """
                              select name
                              from sys.databases
                              where state = 0
                                and has_dbaccess(name) = 1
                              order by name;
                              """;
        using var reader = command.ExecuteReader();
        var names = new List<string>();
        while (reader.Read())
            names.Add(reader.GetString(0));
        return names;
    }

    public override string GetTableStatement()
    {
        return "select table_name as name from information_schema.tables where table_type = 'BASE TABLE'";
    }

    public override string GetViewStatement()
    {
        return "select table_name as name from information_schema.views order by table_name";
    }
    
    public override string GetColumnStatement()
    {
        var sb = new StringBuilder();

        sb.AppendLine("SELECT ");
        sb.AppendLine("    c.name AS [Name],");
        sb.AppendLine("    t.name AS DataType,");
        sb.AppendLine("    CASE ");
        sb.AppendLine("        WHEN t.name IN ('nvarchar', 'nchar') AND c.max_length > 0 ");
        sb.AppendLine("            THEN CAST(c.max_length / 2 AS VARCHAR)");
        sb.AppendLine("        WHEN t.name IN ('varchar', 'char', 'varbinary') AND c.max_length > 0 ");
        sb.AppendLine("            THEN CAST(c.max_length AS VARCHAR)");
        sb.AppendLine("        ELSE CAST(c.max_length AS VARCHAR)");
        sb.AppendLine("    END AS Length,");
        sb.AppendLine("    c.precision AS Precision,");
        sb.AppendLine("    c.scale AS Scale,");
        sb.AppendLine("    c.is_nullable as IsNullable,");
        sb.AppendLine("    CASE WHEN k.column_id IS NOT NULL THEN 1 ELSE 0 END AS IsPrimaryKey,");
        sb.AppendLine("    c.is_identity as IsAutoGenerated,");
        sb.AppendLine("    CASE WHEN c.default_object_id <> 0 THEN 1 ELSE 0 END AS HasDefaultValue");
        sb.AppendLine("FROM ");
        sb.AppendLine("    sys.columns c");
        sb.AppendLine("JOIN ");
        sb.AppendLine("    sys.types t ON c.user_type_id = t.user_type_id");
        sb.AppendLine("LEFT JOIN (");
        sb.AppendLine("    SELECT ic.object_id, ic.column_id");
        sb.AppendLine("    FROM sys.indexes i");
        sb.AppendLine("    INNER JOIN sys.index_columns ic ON i.object_id = ic.object_id AND i.index_id = ic.index_id");
        sb.AppendLine("    WHERE i.is_primary_key = 1");
        sb.AppendLine(") k ON c.object_id = k.object_id AND c.column_id = k.column_id");
        sb.AppendLine("WHERE ");
        sb.AppendLine("    c.object_id = OBJECT_ID(@TableName)");
        sb.AppendLine("ORDER BY ");
        sb.AppendLine("    c.column_id;");
        
        return sb.ToString();
    }

    public override string GetProcedureStatement()
    {
        return """
               select
                   concat(r.routine_schema, '.', r.routine_name) as Name,
                   concat(r.routine_schema, '.', r.routine_name) as SpecificName
               from information_schema.routines r
               inner join sys.objects o
                   on o.object_id = object_id(quotename(r.routine_schema) + '.' + quotename(r.routine_name))
               where r.routine_type = 'PROCEDURE'
                 and r.routine_schema not in ('sys', 'INFORMATION_SCHEMA')
                 and o.is_ms_shipped = 0
               order by r.routine_schema, r.routine_name;
               """;
    }

    public override string GetFunctionStatement()
    {
        return """
               select
                   concat(r.routine_schema, '.', r.routine_name) as Name,
                   concat(r.routine_schema, '.', r.routine_name) as SpecificName,
                   r.data_type as DataType
               from information_schema.routines r
               inner join sys.objects o
                   on o.object_id = object_id(quotename(r.routine_schema) + '.' + quotename(r.routine_name))
               where r.routine_type = 'FUNCTION'
                 and r.routine_schema not in ('sys', 'INFORMATION_SCHEMA')
                 and o.is_ms_shipped = 0
               order by r.routine_schema, r.routine_name;
               """;
    }

    public override string GetRoutineParameterStatement()
    {
        return """
               select
                   coalesce(p.parameter_name, '@RETURN_VALUE') as Name,
                   p.data_type as DataType,
                   coalesce(p.character_maximum_length, 0) as Length,
                   coalesce(p.numeric_precision, 0) as Precision,
                   coalesce(p.numeric_scale, 0) as Scale,
                   cast(0 as bit) as IsNullable,
                   p.parameter_mode as Mode,
                   p.ordinal_position as Position
               from information_schema.parameters p
               where concat(p.specific_schema, '.', p.specific_name) = @SpecificName
               order by p.ordinal_position;
               """;
    }

    public override string GetColumnDefaultValueStatement()
    {
        return """
               select
                   c.name as ColumnName,
                   dc.definition as DefaultValueExpression,
                   dc.name as DefaultConstraintName
               from sys.columns c
               left join sys.default_constraints dc
                   on dc.parent_object_id = c.object_id and dc.parent_column_id = c.column_id
               where c.object_id = OBJECT_ID(@TableName)
               order by c.column_id;
               """;
    }

    public override string GetPrimaryKeyStatement()
    {
        return """
               select
                   kc.name as ConstraintName,
                   c.name as ColumnName,
                   ic.key_ordinal as OrdinalPosition
               from sys.key_constraints kc
               join sys.indexes i on i.object_id = kc.parent_object_id and i.index_id = kc.unique_index_id
               join sys.index_columns ic on ic.object_id = i.object_id and ic.index_id = i.index_id and ic.key_ordinal > 0
               join sys.columns c on c.object_id = ic.object_id and c.column_id = ic.column_id
               where kc.parent_object_id = OBJECT_ID(@TableName) and kc.type = 'PK'
               order by ic.key_ordinal;
               """;
    }

    public override string GetForeignKeyStatement()
    {
        return """
               select
                   fk.name as ConstraintName,
                   pc.name as ColumnName,
                   fkc.constraint_column_id as OrdinalPosition,
                   rs.name as ReferencedSchemaName,
                   rt.name as ReferencedTableName,
                   rc.name as ReferencedColumnName,
                   case fk.delete_referential_action
                       when 1 then 'cascade' when 2 then 'set null' when 3 then 'set default' else '' end as OnDeleteAction,
                   case fk.update_referential_action
                       when 1 then 'cascade' when 2 then 'set null' when 3 then 'set default' else '' end as OnUpdateAction
               from sys.foreign_keys fk
               join sys.foreign_key_columns fkc on fkc.constraint_object_id = fk.object_id
               join sys.columns pc on pc.object_id = fkc.parent_object_id and pc.column_id = fkc.parent_column_id
               join sys.columns rc on rc.object_id = fkc.referenced_object_id and rc.column_id = fkc.referenced_column_id
               join sys.tables rt on rt.object_id = fk.referenced_object_id
               join sys.schemas rs on rs.schema_id = rt.schema_id
               where fk.parent_object_id = OBJECT_ID(@TableName)
               order by fk.name, fkc.constraint_column_id;
               """;
    }

    public override string GetIndexStatement()
    {
        return """
               select
                   i.name as IndexName,
                   i.is_unique as IsUnique,
                   c.name as ColumnName,
                   ic.is_descending_key as IsDescending,
                   ic.key_ordinal as OrdinalPosition,
                   cast(case when i.type = 1 then 1 else 0 end as bit) as IsClustered,
                   nullif(i.fill_factor, 0) as [FillFactor]
               from sys.indexes i
               join sys.index_columns ic on ic.object_id = i.object_id and ic.index_id = i.index_id and ic.key_ordinal > 0
               join sys.columns c on c.object_id = ic.object_id and c.column_id = ic.column_id
               where i.object_id = OBJECT_ID(@TableName)
                 and i.is_primary_key = 0
                 and i.is_unique_constraint = 0
                 and i.is_hypothetical = 0
                 and i.type in (1, 2)
               order by i.name, ic.key_ordinal;
               """;
    }

    private string BuildConnectionString(string? databaseName)
    {
        var builder = new SqlConnectionStringBuilder
        {
            DataSource = BuildDataSource(),
            InitialCatalog = string.IsNullOrWhiteSpace(databaseName) ? "master" : databaseName,
            Encrypt = ConnectionSettings.Encrypt,
            TrustServerCertificate = ConnectionSettings.TrustServerCertificate
        };

        if (ConnectionSettings.AuthenticationMode == SqlServerAuthenticationMode.WindowsIntegrated)
        {
            builder.IntegratedSecurity = true;
        }
        else
        {
            builder.UserID = ConnectionSettings.User;
            builder.Password = ConnectionSettings.Password;
        }

        return builder.ConnectionString;
    }

    private string BuildDataSource()
    {
        if (string.IsNullOrWhiteSpace(ConnectionSettings.Server))
            return ConnectionSettings.Server;

        if (ConnectionSettings.Server.Contains(",", StringComparison.Ordinal) ||
            ConnectionSettings.Server.Contains(":", StringComparison.Ordinal) ||
            ConnectionSettings.Server.Contains("\\", StringComparison.Ordinal))
        {
            return ConnectionSettings.Server;
        }

        return ConnectionSettings.Port > 0
            ? $"{ConnectionSettings.Server},{ConnectionSettings.Port}"
            : ConnectionSettings.Server;
    }
}
