drop view if exists open_orders;
drop procedure if exists mark_order_shipped(integer);
drop function if exists get_customer_total(integer);
drop table if exists orders;
drop table if exists customers;

create table customers
(
    customer_id integer generated by default as identity primary key,
    name varchar(100) not null,
    email varchar(150),
    created_at timestamp default current_timestamp not null
);

create table orders
(
    order_id integer generated by default as identity primary key,
    customer_id integer not null references customers(customer_id),
    order_total numeric(10,2) not null,
    status varchar(30) default 'OPEN' not null,
    created_at timestamp default current_timestamp not null
);

insert into customers (name, email)
values
    ('Alice Johnson', 'alice@example.com'),
    ('Bob Smith', 'bob@example.com');

insert into orders (customer_id, order_total, status)
values
    (1, 149.90, 'OPEN'),
    (2, 79.50, 'SHIPPED');

create view open_orders as
select
    o.order_id,
    c.name as customer_name,
    o.order_total,
    o.status,
    o.created_at
from orders o
join customers c on c.customer_id = o.customer_id
where o.status = 'OPEN';

create or replace procedure mark_order_shipped
(
    p_order_id integer
)
language plpgsql
as $$
begin
    update orders
    set status = 'SHIPPED'
    where order_id = p_order_id;
end;
$$;

create or replace function get_customer_total
(
    p_customer_id integer
)
returns numeric(10,2)
language plpgsql
as $$
declare
    v_total numeric(10,2);
begin
    select coalesce(sum(order_total), 0)
    into v_total
    from orders
    where customer_id = p_customer_id;

    return v_total;
end;
$$;
