using DataDeveloper.Data.Enums;
using DataDeveloper.Data.Interfaces;
using DataDeveloper.Data.Models;
using DataDeveloper.Data.Models.TableDesigner;
using DataDeveloper.Data.Services.Metadata;
using DataDeveloper.Data.Services.SqlDialects;

namespace DataDeveloper.Data.Services.TableDesigner;

/// <summary>
/// Loads a full <see cref="TableDefinition"/> (columns with default values, primary key,
/// foreign keys, indexes) for an existing table, so it can be pre-populated into the table
/// designer for editing. Column shape (name/type/length/precision/scale/nullable/identity)
/// is taken from already-loaded <see cref="ColumnModel"/> rows (schema explorer); this loader
/// only fetches the pieces the schema explorer does not already have.
/// </summary>
public static class TableDefinitionLoader
{
    public static async Task<TableDefinition> LoadAsync(
        IConnectionSettings connectionSettings,
        string schemaName,
        string tableName,
        IReadOnlyList<ColumnModel> loadedColumns)
    {
        var table = new DbObjectRef(DbObjectKind.Table, string.IsNullOrWhiteSpace(schemaName) ? null : schemaName, tableName);
        var structure = await new SchemaMetadataService(connectionSettings).GetTableStructureAsync(table);
        return Build(connectionSettings.DatabaseType, schemaName, tableName, loadedColumns, structure);
    }

    /// <summary>
    /// Combines the explorer's loaded columns with the catalog's table structure.
    /// </summary>
    public static TableDefinition Build(
        DatabaseType databaseType,
        string schemaName,
        string tableName,
        IReadOnlyList<ColumnModel> loadedColumns,
        TableStructure structure)
    {
        var defaultValueRowByColumn = structure.ColumnDefaults
            .Where(row => !string.IsNullOrWhiteSpace(row.ColumnName))
            .ToDictionary(row => row.ColumnName, row => row, StringComparer.OrdinalIgnoreCase);
        var primaryKeyRows = structure.PrimaryKeyColumns;
        var foreignKeyRows = structure.ForeignKeyColumns;
        var indexRows = structure.IndexColumns;

        // Names read from the database are stored names; the definition holds them in the form
        // the DDL builder formats back to the same object (e.g. quoted when Oracle would
        // otherwise upper-case them).
        var dialect = SqlDialect.For(databaseType);
        string Name(string? storedName) => string.IsNullOrEmpty(storedName) ? string.Empty : dialect.ToFormattableName(storedName);

        var table = new TableDefinition
        {
            SchemaName = Name(schemaName),
            TableName = Name(tableName)
        };

        var primaryKeyColumnNames = primaryKeyRows
            .Select(row => row.ColumnName)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        foreach (var column in loadedColumns)
        {
            defaultValueRowByColumn.TryGetValue(column.Name, out var defaultValueRow);

            var columnDefinition = new TableColumnDefinition
            {
                OriginalName = Name(column.Name),
                Name = Name(column.Name),
                DataType = NormalizeDataType(databaseType, column.DataType),
                Length = column.Length > 0 ? column.Length : null,
                Precision = column.Precision > 0 ? column.Precision : null,
                Scale = column.Scale > 0 ? column.Scale : null,
                IsNullable = primaryKeyColumnNames.Contains(column.Name) ? false : column.IsNullable,
                IsIdentity = column.IsAutoGenerated,
                DefaultValue = defaultValueRow?.DefaultValueExpression ?? string.Empty
            };

            if (!string.IsNullOrWhiteSpace(defaultValueRow?.DefaultConstraintName))
                columnDefinition.ProviderOptions["default_constraint_name"] = defaultValueRow.DefaultConstraintName!;

            table.Columns.Add(columnDefinition);
        }

        var orderedPrimaryKeyRows = primaryKeyRows.OrderBy(row => row.OrdinalPosition).ToList();
        if (orderedPrimaryKeyRows.Count > 0)
        {
            table.PrimaryKey.Name = Name(orderedPrimaryKeyRows[0].ConstraintName);
            table.PrimaryKey.ColumnNames.AddRange(orderedPrimaryKeyRows.Select(row => Name(row.ColumnName)));
        }

        foreach (var group in foreignKeyRows.GroupBy(row => row.ConstraintName, StringComparer.OrdinalIgnoreCase))
        {
            var orderedRows = group.OrderBy(row => row.OrdinalPosition).ToList();
            var firstRow = orderedRows[0];
            var foreignKey = new TableForeignKeyDefinition
            {
                Name = Name(group.Key),
                ReferencedSchemaName = Name(firstRow.ReferencedSchemaName),
                ReferencedTableName = Name(firstRow.ReferencedTableName),
                OnDeleteAction = firstRow.OnDeleteAction ?? string.Empty,
                OnUpdateAction = firstRow.OnUpdateAction ?? string.Empty
            };
            foreignKey.ColumnNames.AddRange(orderedRows.Select(row => Name(row.ColumnName)));
            foreignKey.ReferencedColumnNames.AddRange(orderedRows.Select(row => Name(row.ReferencedColumnName)));
            table.ForeignKeys.Add(foreignKey);
        }

        foreach (var group in indexRows.GroupBy(row => row.IndexName, StringComparer.OrdinalIgnoreCase))
        {
            var orderedRows = group.OrderBy(row => row.OrdinalPosition).ToList();
            var firstIndexRow = orderedRows[0];
            var index = new TableIndexDefinition
            {
                Name = Name(group.Key),
                IsUnique = firstIndexRow.IsUnique
            };

            if (firstIndexRow.IsClustered == true)
                index.ProviderOptions["clustered"] = "true";
            if (firstIndexRow.FillFactor is > 0)
                index.ProviderOptions["fillfactor"] = firstIndexRow.FillFactor.Value.ToString();
            if (!string.IsNullOrWhiteSpace(firstIndexRow.UsingMethod) &&
                !string.Equals(firstIndexRow.UsingMethod, "btree", StringComparison.OrdinalIgnoreCase))
            {
                index.ProviderOptions["using"] = firstIndexRow.UsingMethod;
            }
            if (!string.IsNullOrWhiteSpace(firstIndexRow.WherePredicate))
                index.ProviderOptions["where"] = firstIndexRow.WherePredicate;

            foreach (var row in orderedRows)
            {
                var indexColumn = new TableIndexColumnDefinition
                {
                    Name = Name(row.ColumnName),
                    Descending = row.IsDescending
                };

                if (row.PrefixLength is > 0)
                    indexColumn.ProviderOptions["prefix_length"] = row.PrefixLength.Value.ToString();

                index.Columns.Add(indexColumn);
            }

            table.Indexes.Add(index);
        }

        return table;
    }

    private static string NormalizeDataType(DatabaseType databaseType, string dataType)
    {
        if (databaseType != DatabaseType.PostgresSql)
            return dataType;

        return dataType.Trim().ToLowerInvariant() switch
        {
            "character varying" => "varchar",
            "character" => "char",
            "timestamp without time zone" => "timestamp",
            "time without time zone" => "time",
            _ => dataType
        };
    }
}
