using System.Data;
using Dapper;
using DataDeveloper.Data.Enums;
using DataDeveloper.Data.Interfaces;
using DataDeveloper.Data.Models;
using DataDeveloper.Data.Models.TableDesigner;

namespace DataDeveloper.Data.Services.TableDesigner;

/// <summary>
/// Loads a full <see cref="TableDefinition"/> (columns with default values, primary key,
/// foreign keys, indexes) for an existing table, so it can be pre-populated into the table
/// designer for editing. Column shape (name/type/length/precision/scale/nullable/identity)
/// is taken from already-loaded <see cref="ColumnModel"/> rows (schema explorer); this loader
/// only fetches the pieces the schema explorer does not already have.
/// </summary>
public static class TableDefinitionLoader
{
    public static async Task<TableDefinition> LoadAsync(
        IConnectionSettings connectionSettings,
        string schemaName,
        string tableName,
        IReadOnlyList<ColumnModel> loadedColumns)
    {
        var databaseProvider = connectionSettings.GetDatabaseProvider();
        await using var connection = databaseProvider.GetConnection();
        await connection.OpenAsync();

        var defaultValues = await QueryAsync<ColumnDefaultValueRow>(
            connection, databaseProvider.GetColumnDefaultValueStatement(), connectionSettings.DatabaseType, tableName);
        var defaultValueRowByColumn = defaultValues
            .Where(row => !string.IsNullOrWhiteSpace(row.ColumnName))
            .ToDictionary(row => row.ColumnName, row => row, StringComparer.OrdinalIgnoreCase);

        var primaryKeyRows = await QueryAsync<PrimaryKeyColumnRow>(
            connection, databaseProvider.GetPrimaryKeyStatement(), connectionSettings.DatabaseType, tableName);
        var foreignKeyRows = await QueryAsync<ForeignKeyColumnRow>(
            connection, databaseProvider.GetForeignKeyStatement(), connectionSettings.DatabaseType, tableName);
        var indexRows = await QueryAsync<IndexColumnRow>(
            connection, databaseProvider.GetIndexStatement(), connectionSettings.DatabaseType, tableName);

        var table = new TableDefinition
        {
            SchemaName = schemaName,
            TableName = tableName
        };

        var primaryKeyColumnNames = primaryKeyRows
            .Select(row => row.ColumnName)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        foreach (var column in loadedColumns)
        {
            defaultValueRowByColumn.TryGetValue(column.Name, out var defaultValueRow);

            var columnDefinition = new TableColumnDefinition
            {
                OriginalName = column.Name,
                Name = column.Name,
                DataType = NormalizeDataType(connectionSettings.DatabaseType, column.DataType),
                Length = column.Length > 0 ? column.Length : null,
                Precision = column.Precision > 0 ? column.Precision : null,
                Scale = column.Scale > 0 ? column.Scale : null,
                IsNullable = primaryKeyColumnNames.Contains(column.Name) ? false : column.IsNullable,
                IsIdentity = column.IsAutoGenerated,
                DefaultValue = defaultValueRow?.DefaultValueExpression ?? string.Empty
            };

            if (!string.IsNullOrWhiteSpace(defaultValueRow?.DefaultConstraintName))
                columnDefinition.ProviderOptions["default_constraint_name"] = defaultValueRow.DefaultConstraintName!;

            table.Columns.Add(columnDefinition);
        }

        var orderedPrimaryKeyRows = primaryKeyRows.OrderBy(row => row.OrdinalPosition).ToList();
        if (orderedPrimaryKeyRows.Count > 0)
        {
            table.PrimaryKey.Name = orderedPrimaryKeyRows[0].ConstraintName ?? string.Empty;
            table.PrimaryKey.ColumnNames.AddRange(orderedPrimaryKeyRows.Select(row => row.ColumnName));
        }

        foreach (var group in foreignKeyRows.GroupBy(row => row.ConstraintName, StringComparer.OrdinalIgnoreCase))
        {
            var orderedRows = group.OrderBy(row => row.OrdinalPosition).ToList();
            var firstRow = orderedRows[0];
            var foreignKey = new TableForeignKeyDefinition
            {
                Name = group.Key,
                ReferencedSchemaName = firstRow.ReferencedSchemaName ?? string.Empty,
                ReferencedTableName = firstRow.ReferencedTableName ?? string.Empty,
                OnDeleteAction = firstRow.OnDeleteAction ?? string.Empty,
                OnUpdateAction = firstRow.OnUpdateAction ?? string.Empty
            };
            foreignKey.ColumnNames.AddRange(orderedRows.Select(row => row.ColumnName));
            foreignKey.ReferencedColumnNames.AddRange(orderedRows.Select(row => row.ReferencedColumnName));
            table.ForeignKeys.Add(foreignKey);
        }

        foreach (var group in indexRows.GroupBy(row => row.IndexName, StringComparer.OrdinalIgnoreCase))
        {
            var orderedRows = group.OrderBy(row => row.OrdinalPosition).ToList();
            var firstIndexRow = orderedRows[0];
            var index = new TableIndexDefinition
            {
                Name = group.Key,
                IsUnique = firstIndexRow.IsUnique
            };

            if (firstIndexRow.IsClustered == true)
                index.ProviderOptions["clustered"] = "true";
            if (firstIndexRow.FillFactor is > 0)
                index.ProviderOptions["fillfactor"] = firstIndexRow.FillFactor.Value.ToString();
            if (!string.IsNullOrWhiteSpace(firstIndexRow.UsingMethod) &&
                !string.Equals(firstIndexRow.UsingMethod, "btree", StringComparison.OrdinalIgnoreCase))
            {
                index.ProviderOptions["using"] = firstIndexRow.UsingMethod;
            }
            if (!string.IsNullOrWhiteSpace(firstIndexRow.WherePredicate))
                index.ProviderOptions["where"] = firstIndexRow.WherePredicate;

            foreach (var row in orderedRows)
            {
                var indexColumn = new TableIndexColumnDefinition
                {
                    Name = row.ColumnName,
                    Descending = row.IsDescending
                };

                if (row.PrefixLength is > 0)
                    indexColumn.ProviderOptions["prefix_length"] = row.PrefixLength.Value.ToString();

                index.Columns.Add(indexColumn);
            }

            table.Indexes.Add(index);
        }

        return table;
    }

    private static string NormalizeDataType(DatabaseType databaseType, string dataType)
    {
        if (databaseType != DatabaseType.PostgresSql)
            return dataType;

        return dataType.Trim().ToLowerInvariant() switch
        {
            "character varying" => "varchar",
            "character" => "char",
            "timestamp without time zone" => "timestamp",
            "time without time zone" => "time",
            _ => dataType
        };
    }

    private static async Task<IEnumerable<T>> QueryAsync<T>(
        System.Data.Common.DbConnection connection, string statement, DatabaseType databaseType, string tableName)
    {
        if (databaseType == DatabaseType.SqLite)
        {
            var escapedTableName = tableName.Replace("'", "''", StringComparison.Ordinal);
            statement = statement.Replace("__table_name__", $"'{escapedTableName}'", StringComparison.Ordinal);
            return await connection.QueryAsync<T>(statement, commandType: CommandType.Text);
        }

        return await connection.QueryAsync<T>(statement, param: new { TableName = tableName }, commandType: CommandType.Text);
    }

    private sealed class ColumnDefaultValueRow
    {
        public string ColumnName { get; set; } = string.Empty;
        public string? DefaultValueExpression { get; set; }
        public string? DefaultConstraintName { get; set; }
    }

    private sealed class PrimaryKeyColumnRow
    {
        public string? ConstraintName { get; set; }
        public string ColumnName { get; set; } = string.Empty;
        public int OrdinalPosition { get; set; }
    }

    private sealed class ForeignKeyColumnRow
    {
        public string ConstraintName { get; set; } = string.Empty;
        public string ColumnName { get; set; } = string.Empty;
        public int OrdinalPosition { get; set; }
        public string? ReferencedSchemaName { get; set; }
        public string? ReferencedTableName { get; set; }
        public string ReferencedColumnName { get; set; } = string.Empty;
        public string? OnDeleteAction { get; set; }
        public string? OnUpdateAction { get; set; }
    }

    private sealed class IndexColumnRow
    {
        public string IndexName { get; set; } = string.Empty;
        public bool IsUnique { get; set; }
        public string ColumnName { get; set; } = string.Empty;
        public bool IsDescending { get; set; }
        public int OrdinalPosition { get; set; }
        public bool? IsClustered { get; set; }
        public int? FillFactor { get; set; }
        public string? UsingMethod { get; set; }
        public string? WherePredicate { get; set; }
        public int? PrefixLength { get; set; }
    }
}
