using DataDeveloper.Data.Services.Metadata;
using DataDeveloper.Data.Enums;
using DataDeveloper.Data.Providers.SqLite;
using Microsoft.Data.Sqlite;
using Xunit;

namespace DataDeveloper.Tests.Providers;

public class SqLiteDatabaseProviderTests
{
    [Fact]
    public void GetConnection_ReturnsSqliteConnection()
    {
        var provider = new SqLiteDatabaseProvider(new SqLiteConnectionSettings
        {
            Database = "/tmp/app.db"
        });

        var connection = provider.GetConnection();

        var sqliteConnection = Assert.IsType<SqliteConnection>(connection);
        var builder = new SqliteConnectionStringBuilder(sqliteConnection.ConnectionString);
        Assert.Equal("/tmp/app.db", builder.DataSource);
    }

    [Fact]
    public void GetTableStatement_UsesSqliteMaster()
    {
        var catalog = ObjectCatalog.For(DatabaseType.SqLite);

        var sql = catalog.GetObjectListStatement(DbObjectKind.Table);

        Assert.Contains("from sqlite_master", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("type = 'table'", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GetColumnStatement_UsesPragmaTableInfo()
    {
        var catalog = ObjectCatalog.For(DatabaseType.SqLite);

        var sql = catalog.GetColumnsStatement();

        Assert.Contains("pragma_table_info(@TableName)", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("p.\"notnull\"", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("IsAutoGenerated", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("HasDefaultValue", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GetViewStatement_UsesSqliteMaster()
    {
        var catalog = ObjectCatalog.For(DatabaseType.SqLite);

        var sql = catalog.GetObjectListStatement(DbObjectKind.View);

        Assert.Contains("from sqlite_master", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("type = 'view'", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GetProcedureStatement_ReturnsEmptyProjection()
    {
        var catalog = ObjectCatalog.For(DatabaseType.SqLite);

        var sql = catalog.GetObjectListStatement(DbObjectKind.Procedure);

        Assert.Contains("where 1 = 0", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GetFunctionStatement_ReturnsEmptyProjection()
    {
        var catalog = ObjectCatalog.For(DatabaseType.SqLite);

        var sql = catalog.GetObjectListStatement(DbObjectKind.Function);

        Assert.Contains("where 1 = 0", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GetRoutineParameterStatement_ReturnsEmptyProjection()
    {
        var catalog = ObjectCatalog.For(DatabaseType.SqLite);

        var sql = catalog.GetRoutineParametersStatement();

        Assert.Contains("where 1 = 0", sql, StringComparison.OrdinalIgnoreCase);
    }
}
