using DataDeveloper.Data.Providers.SqlServer;
using Microsoft.Data.SqlClient;
using Xunit;

namespace DataDeveloper.Tests.Providers;

public class SqlServerDatabaseProviderTests
{
    [Fact]
    public void GetConnection_ReturnsSqlConnection()
    {
        var provider = new SqlServerDatabaseProvider(new SqlServerConnectionSettings
        {
            Server = "localhost",
            Database = "master",
            AuthenticationMode = SqlServerAuthenticationMode.SqlLogin,
            User = "sa",
            Password = "pwd",
            Encrypt = true,
            TrustServerCertificate = false
        });

        var connection = provider.GetConnection();

        var sqlConnection = Assert.IsType<SqlConnection>(connection);
        var builder = new SqlConnectionStringBuilder(sqlConnection.ConnectionString);
        Assert.Equal("localhost", builder.DataSource);
        Assert.Equal("master", builder.InitialCatalog);
        Assert.True(builder.Encrypt);
        Assert.False(builder.TrustServerCertificate);
        Assert.False(builder.IntegratedSecurity);
        Assert.Equal("sa", builder.UserID);
        Assert.Equal("pwd", builder.Password);
    }

    [Fact]
    public void GetConnection_UsesIntegratedSecurity_ForWindowsAuthentication()
    {
        var provider = new SqlServerDatabaseProvider(new SqlServerConnectionSettings
        {
            Server = @"(localdb)\MSSQLLocalDB",
            Database = "master",
            AuthenticationMode = SqlServerAuthenticationMode.WindowsIntegrated,
            User = "sa",
            Password = "pwd",
            Encrypt = true,
            TrustServerCertificate = true
        });

        var connection = provider.GetConnection();

        var sqlConnection = Assert.IsType<SqlConnection>(connection);
        var builder = new SqlConnectionStringBuilder(sqlConnection.ConnectionString);
        Assert.Equal(@"(localdb)\MSSQLLocalDB", builder.DataSource);
        Assert.Equal("master", builder.InitialCatalog);
        Assert.True(builder.IntegratedSecurity);
        Assert.True(builder.Encrypt);
        Assert.True(builder.TrustServerCertificate);
        Assert.True(string.IsNullOrEmpty(builder.UserID));
        Assert.True(string.IsNullOrEmpty(builder.Password));
    }

    [Fact]
    public void GetTableStatement_UsesInformationSchemaTables()
    {
        var provider = new SqlServerDatabaseProvider(new SqlServerConnectionSettings());

        var sql = provider.GetTableStatement();

        Assert.Contains("information_schema.tables", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("table_type = 'BASE TABLE'", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GetColumnStatement_UsesSysCatalogs()
    {
        var provider = new SqlServerDatabaseProvider(new SqlServerConnectionSettings());

        var sql = provider.GetColumnStatement();

        Assert.Contains("sys.columns", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("sys.types", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("OBJECT_ID(@TableName)", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("IsAutoGenerated", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("HasDefaultValue", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GetViewStatement_UsesInformationSchemaViews()
    {
        var provider = new SqlServerDatabaseProvider(new SqlServerConnectionSettings());

        var sql = provider.GetViewStatement();

        Assert.Contains("information_schema.views", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GetProcedureStatement_UsesInformationSchemaRoutines()
    {
        var provider = new SqlServerDatabaseProvider(new SqlServerConnectionSettings());

        var sql = provider.GetProcedureStatement();

        Assert.Contains("information_schema.routines", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("sys.objects", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("routine_type = 'PROCEDURE'", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("is_ms_shipped = 0", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GetFunctionStatement_UsesInformationSchemaRoutines()
    {
        var provider = new SqlServerDatabaseProvider(new SqlServerConnectionSettings());

        var sql = provider.GetFunctionStatement();

        Assert.Contains("information_schema.routines", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("sys.objects", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("routine_type = 'FUNCTION'", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("is_ms_shipped = 0", sql, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GetRoutineParameterStatement_UsesInformationSchemaParameters()
    {
        var provider = new SqlServerDatabaseProvider(new SqlServerConnectionSettings());

        var sql = provider.GetRoutineParameterStatement();

        Assert.Contains("information_schema.parameters", sql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("concat(p.specific_schema, '.', p.specific_name) = @SpecificName", sql, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("is_nullable", sql, StringComparison.OrdinalIgnoreCase);
    }
}
