using System.Data.Common;
using System.Text;
using DataDeveloper.Data.Services;
using Npgsql;

namespace DataDeveloper.Data.Providers.PostgresSql;

public class PostgresDatabaseProvider : DatabaseProviderBase<PostgresConnectionSettings>
{
    public PostgresDatabaseProvider(PostgresConnectionSettings connectionSettings)
        : base(connectionSettings)
    {
    }

    public override DbConnection GetConnection()
    {
        var sslMode = ConnectionSettings.Encrypt
            ? ConnectionSettings.TrustServerCertificate
                ? SslMode.Require
                : SslMode.VerifyCA
            : SslMode.Disable;

        var connectionStringBuilder = new NpgsqlConnectionStringBuilder
        {
            Host = ConnectionSettings.Server,
            Database = ConnectionSettings.Database,
            Username = ConnectionSettings.User,
            Password = ConnectionSettings.Password,
            Port = ConnectionSettings.Port,
            SslMode = sslMode,
            TrustServerCertificate = ConnectionSettings.TrustServerCertificate
        };

        return new NpgsqlConnection(connectionStringBuilder.ConnectionString);
    }

    public override IReadOnlyList<string> GetAvailableDatabaseNames()
    {
        using var connection = new NpgsqlConnection(BuildConnectionString("postgres"));
        connection.Open();
        using var command = connection.CreateCommand();
        command.CommandText = """
                              select datname
                              from pg_database
                              where datallowconn
                                and not datistemplate
                              order by datname;
                              """;
        using var reader = command.ExecuteReader();
        var names = new List<string>();
        while (reader.Read())
            names.Add(reader.GetString(0));
        return names;
    }

    public override string GetTableStatement()
    {
        return """
               select table_name as Name
               from information_schema.tables
               where table_schema = current_schema()
                 and table_type = 'BASE TABLE'
               order by table_name;
               """;
    }

    public override string GetViewStatement()
    {
        return """
               select table_name as Name
               from information_schema.views
               where table_schema = current_schema()
               order by table_name;
               """;
    }

    public override string GetColumnStatement()
    {
        var sb = new StringBuilder();

        // IsPrimaryKey is computed with an EXISTS subquery scoped to PRIMARY KEY constraints
        // only. A join against key_column_usage without that scoping (as this used to do)
        // also matches foreign-key columns, since key_column_usage lists every constraint
        // type, not just primary keys - that previously caused the WHERE filter to silently
        // drop foreign-key columns from the result entirely instead of just mis-flagging them.
        sb.AppendLine("select");
        sb.AppendLine("    c.column_name as \"Name\",");
        sb.AppendLine("    c.data_type as \"DataType\",");
        sb.AppendLine("    coalesce(c.character_maximum_length, 0) as \"Length\",");
        sb.AppendLine("    coalesce(c.numeric_precision, 0) as \"Precision\",");
        sb.AppendLine("    coalesce(c.numeric_scale, 0) as \"Scale\",");
        sb.AppendLine("    case when c.is_nullable = 'YES' then true else false end as \"IsNullable\",");
        sb.AppendLine("    exists (");
        sb.AppendLine("        select 1");
        sb.AppendLine("        from information_schema.table_constraints tc");
        sb.AppendLine("        join information_schema.key_column_usage kcu");
        sb.AppendLine("            on kcu.constraint_schema = tc.constraint_schema");
        sb.AppendLine("           and kcu.constraint_name = tc.constraint_name");
        sb.AppendLine("        where tc.table_schema = c.table_schema");
        sb.AppendLine("          and tc.table_name = c.table_name");
        sb.AppendLine("          and tc.constraint_type = 'PRIMARY KEY'");
        sb.AppendLine("          and kcu.column_name = c.column_name");
        sb.AppendLine("    ) as \"IsPrimaryKey\",");
        sb.AppendLine("    case when c.is_identity = 'YES' or c.is_generated = 'ALWAYS' then true else false end as \"IsAutoGenerated\",");
        sb.AppendLine("    case when c.column_default is not null then true else false end as \"HasDefaultValue\"");
        sb.AppendLine("from information_schema.columns c");
        sb.AppendLine("where c.table_schema = current_schema()");
        sb.AppendLine("  and c.table_name = @TableName");
        sb.AppendLine("order by c.ordinal_position;");

        return sb.ToString();
    }

    public override string GetProcedureStatement()
    {
        return """
               select
                   routine_name as Name,
                   specific_name as SpecificName
               from information_schema.routines
               where specific_schema = current_schema()
                 and routine_type = 'PROCEDURE'
               order by routine_name;
               """;
    }

    public override string GetFunctionStatement()
    {
        return """
               select
                   routine_name as Name,
                   specific_name as SpecificName,
                   data_type as DataType
               from information_schema.routines
               where specific_schema = current_schema()
                 and routine_type = 'FUNCTION'
               order by routine_name;
               """;
    }

    public override string GetRoutineParameterStatement()
    {
        return """
               select
                   coalesce(parameter_name, 'return') as Name,
                   data_type as DataType,
                   coalesce(character_maximum_length, 0) as Length,
                   coalesce(numeric_precision, 0) as Precision,
                   coalesce(numeric_scale, 0) as Scale,
                   true as IsNullable,
                   parameter_mode as Mode,
                   ordinal_position as Position
               from information_schema.parameters
               where specific_schema = current_schema()
                 and specific_name = @SpecificName
               order by ordinal_position;
               """;
    }

    private string BuildConnectionString(string? databaseName)
    {
        var sslMode = ConnectionSettings.Encrypt
            ? ConnectionSettings.TrustServerCertificate
                ? SslMode.Require
                : SslMode.VerifyCA
            : SslMode.Disable;

        var connectionStringBuilder = new NpgsqlConnectionStringBuilder
        {
            Host = ConnectionSettings.Server,
            Database = string.IsNullOrWhiteSpace(databaseName) ? "postgres" : databaseName,
            Username = ConnectionSettings.User,
            Password = ConnectionSettings.Password,
            Port = ConnectionSettings.Port,
            SslMode = sslMode,
            TrustServerCertificate = ConnectionSettings.TrustServerCertificate
        };

        return connectionStringBuilder.ConnectionString;
    }
}
