using System.Data.Common;
using System.Text;
using DataDeveloper.Data.Services;
using Npgsql;

namespace DataDeveloper.Data.Providers.PostgresSql;

public class PostgresDatabaseProvider : DatabaseProviderBase<PostgresConnectionSettings>
{
    public PostgresDatabaseProvider(PostgresConnectionSettings connectionSettings)
        : base(connectionSettings)
    {
    }

    public override DbConnection GetConnection()
    {
        var sslMode = ConnectionSettings.Encrypt
            ? ConnectionSettings.TrustServerCertificate
                ? SslMode.Require
                : SslMode.VerifyCA
            : SslMode.Disable;

        var connectionStringBuilder = new NpgsqlConnectionStringBuilder
        {
            Host = ConnectionSettings.Server,
            Database = ConnectionSettings.Database,
            Username = ConnectionSettings.User,
            Password = ConnectionSettings.Password,
            Port = ConnectionSettings.Port,
            SslMode = sslMode,
            TrustServerCertificate = ConnectionSettings.TrustServerCertificate
        };

        return new NpgsqlConnection(connectionStringBuilder.ConnectionString);
    }

    public override IReadOnlyList<string> GetAvailableDatabaseNames()
    {
        using var connection = new NpgsqlConnection(BuildConnectionString("postgres"));
        connection.Open();
        using var command = connection.CreateCommand();
        command.CommandText = """
                              select datname
                              from pg_database
                              where datallowconn
                                and not datistemplate
                              order by datname;
                              """;
        using var reader = command.ExecuteReader();
        var names = new List<string>();
        while (reader.Read())
            names.Add(reader.GetString(0));
        return names;
    }

    public override string GetTableStatement()
    {
        return """
               select table_name as Name
               from information_schema.tables
               where table_schema = current_schema()
                 and table_type = 'BASE TABLE'
               order by table_name;
               """;
    }

    public override string GetViewStatement()
    {
        return """
               select table_name as Name
               from information_schema.views
               where table_schema = current_schema()
               order by table_name;
               """;
    }

    public override string GetColumnStatement()
    {
        var sb = new StringBuilder();

        // IsPrimaryKey is computed with an EXISTS subquery scoped to PRIMARY KEY constraints
        // only. A join against key_column_usage without that scoping (as this used to do)
        // also matches foreign-key columns, since key_column_usage lists every constraint
        // type, not just primary keys - that previously caused the WHERE filter to silently
        // drop foreign-key columns from the result entirely instead of just mis-flagging them.
        sb.AppendLine("select");
        sb.AppendLine("    c.column_name as \"Name\",");
        sb.AppendLine("    c.data_type as \"DataType\",");
        sb.AppendLine("    coalesce(c.character_maximum_length, 0) as \"Length\",");
        sb.AppendLine("    coalesce(c.numeric_precision, 0) as \"Precision\",");
        sb.AppendLine("    coalesce(c.numeric_scale, 0) as \"Scale\",");
        sb.AppendLine("    case when c.is_nullable = 'YES' then true else false end as \"IsNullable\",");
        sb.AppendLine("    exists (");
        sb.AppendLine("        select 1");
        sb.AppendLine("        from information_schema.table_constraints tc");
        sb.AppendLine("        join information_schema.key_column_usage kcu");
        sb.AppendLine("            on kcu.constraint_schema = tc.constraint_schema");
        sb.AppendLine("           and kcu.constraint_name = tc.constraint_name");
        sb.AppendLine("        where tc.table_schema = c.table_schema");
        sb.AppendLine("          and tc.table_name = c.table_name");
        sb.AppendLine("          and tc.constraint_type = 'PRIMARY KEY'");
        sb.AppendLine("          and kcu.column_name = c.column_name");
        sb.AppendLine("    ) as \"IsPrimaryKey\",");
        sb.AppendLine("    case when c.is_identity = 'YES' or c.is_generated = 'ALWAYS' then true else false end as \"IsAutoGenerated\",");
        sb.AppendLine("    case when c.column_default is not null then true else false end as \"HasDefaultValue\"");
        sb.AppendLine("from information_schema.columns c");
        sb.AppendLine("where c.table_schema = current_schema()");
        sb.AppendLine("  and c.table_name = @TableName");
        sb.AppendLine("order by c.ordinal_position;");

        return sb.ToString();
    }

    public override string GetProcedureStatement()
    {
        return """
               select
                   routine_name as Name,
                   specific_name as SpecificName
               from information_schema.routines
               where specific_schema = current_schema()
                 and routine_type = 'PROCEDURE'
               order by routine_name;
               """;
    }

    public override string GetFunctionStatement()
    {
        return """
               select
                   routine_name as Name,
                   specific_name as SpecificName,
                   data_type as DataType
               from information_schema.routines
               where specific_schema = current_schema()
                 and routine_type = 'FUNCTION'
               order by routine_name;
               """;
    }

    public override string GetRoutineParameterStatement()
    {
        return """
               select
                   coalesce(parameter_name, 'return') as Name,
                   data_type as DataType,
                   coalesce(character_maximum_length, 0) as Length,
                   coalesce(numeric_precision, 0) as Precision,
                   coalesce(numeric_scale, 0) as Scale,
                   true as IsNullable,
                   parameter_mode as Mode,
                   ordinal_position as Position
               from information_schema.parameters
               where specific_schema = current_schema()
                 and specific_name = @SpecificName
               order by ordinal_position;
               """;
    }

    public override string GetColumnDefaultValueStatement()
    {
        return """
               select
                   column_name as "ColumnName",
                   column_default as "DefaultValueExpression"
               from information_schema.columns
               where table_schema = current_schema()
                 and table_name = @TableName
               order by ordinal_position;
               """;
    }

    public override string GetPrimaryKeyStatement()
    {
        return """
               select
                   tc.constraint_name as "ConstraintName",
                   kcu.column_name as "ColumnName",
                   kcu.ordinal_position as "OrdinalPosition"
               from information_schema.table_constraints tc
               join information_schema.key_column_usage kcu
                   on kcu.constraint_schema = tc.constraint_schema
                  and kcu.constraint_name = tc.constraint_name
               where tc.table_schema = current_schema()
                 and tc.table_name = @TableName
                 and tc.constraint_type = 'PRIMARY KEY'
               order by kcu.ordinal_position;
               """;
    }

    public override string GetForeignKeyStatement()
    {
        return """
               select
                   con.conname as "ConstraintName",
                   att2.attname as "ColumnName",
                   ord.ordinality as "OrdinalPosition",
                   rn.nspname as "ReferencedSchemaName",
                   rc.relname as "ReferencedTableName",
                   att1.attname as "ReferencedColumnName",
                   case con.confdeltype
                       when 'c' then 'cascade' when 'n' then 'set null'
                       when 'd' then 'set default' when 'r' then 'restrict' else '' end as "OnDeleteAction",
                   case con.confupdtype
                       when 'c' then 'cascade' when 'n' then 'set null'
                       when 'd' then 'set default' when 'r' then 'restrict' else '' end as "OnUpdateAction"
               from pg_constraint con
               join pg_class t on t.oid = con.conrelid
               join pg_namespace n on n.oid = t.relnamespace
               join pg_class rc on rc.oid = con.confrelid
               join pg_namespace rn on rn.oid = rc.relnamespace
               cross join lateral unnest(con.conkey, con.confkey) with ordinality as ord(local_attnum, ref_attnum, ordinality)
               join pg_attribute att2 on att2.attrelid = con.conrelid and att2.attnum = ord.local_attnum
               join pg_attribute att1 on att1.attrelid = con.confrelid and att1.attnum = ord.ref_attnum
               where con.contype = 'f'
                 and n.nspname = current_schema()
                 and t.relname = @TableName
               order by con.conname, ord.ordinality;
               """;
    }

    public override string GetIndexStatement()
    {
        return """
               select
                   ic.relname as "IndexName",
                   i.indisunique as "IsUnique",
                   a.attname as "ColumnName",
                   (o.option & 1) = 1 as "IsDescending",
                   o.ordinality as "OrdinalPosition",
                   am.amname as "UsingMethod",
                   pg_get_expr(i.indpred, i.indrelid) as "WherePredicate"
               from pg_index i
               join pg_class t on t.oid = i.indrelid
               join pg_namespace n on n.oid = t.relnamespace
               join pg_class ic on ic.oid = i.indexrelid
               join pg_am am on am.oid = ic.relam
               cross join lateral unnest(i.indkey, i.indoption) with ordinality as o(attnum, option, ordinality)
               join pg_attribute a on a.attrelid = t.oid and a.attnum = o.attnum
               where n.nspname = current_schema()
                 and t.relname = @TableName
                 and not i.indisprimary
                 and not exists (
                     select 1 from pg_constraint con
                     where con.conrelid = t.oid and con.conindid = i.indexrelid
                 )
               order by ic.relname, o.ordinality;
               """;
    }

    private string BuildConnectionString(string? databaseName)
    {
        var sslMode = ConnectionSettings.Encrypt
            ? ConnectionSettings.TrustServerCertificate
                ? SslMode.Require
                : SslMode.VerifyCA
            : SslMode.Disable;

        var connectionStringBuilder = new NpgsqlConnectionStringBuilder
        {
            Host = ConnectionSettings.Server,
            Database = string.IsNullOrWhiteSpace(databaseName) ? "postgres" : databaseName,
            Username = ConnectionSettings.User,
            Password = ConnectionSettings.Password,
            Port = ConnectionSettings.Port,
            SslMode = sslMode,
            TrustServerCertificate = ConnectionSettings.TrustServerCertificate
        };

        return connectionStringBuilder.ConnectionString;
    }
}
