using DataDeveloper.Data.Enums;
using DataDeveloper.Data.Models;
using DataDeveloper.Data.Services.SqlDialects;

namespace DataDeveloper.Data.Services;

public static class EditableResultSetCommandBuilder
{
    public static EditableResultSetCommand? BuildInsert(
        DatabaseType databaseType,
        string tableName,
        IReadOnlyList<string> gridHeaders,
        IReadOnlyList<ColumnModel> tableColumns,
        IReadOnlyList<object?> currentValues)
    {
        var primaryKeys = GetPrimaryKeySet(tableColumns);
        var tableColumnLookup = tableColumns.ToDictionary(column => column.Name, StringComparer.OrdinalIgnoreCase);
        var columns = new List<(string Name, object? Value)>();
        for (var index = 0; index < gridHeaders.Count && index < currentValues.Count; index++)
        {
            var columnName = gridHeaders[index];
            var value = currentValues[index];
            tableColumnLookup.TryGetValue(columnName, out var tableColumn);

            if (primaryKeys.Contains(columnName) && value is null)
                continue;

            if (value is null && tableColumn is not null && (tableColumn.IsAutoGenerated || tableColumn.HasDefaultValue))
                continue;

            columns.Add((columnName, value));
        }

        if (columns.Count == 0)
        {
            var defaultInsertSql = databaseType switch
            {
                DatabaseType.SqlServer => $"insert into {QuoteQualifiedName(databaseType, tableName)} default values;",
                DatabaseType.PostgresSql => $"insert into {QuoteQualifiedName(databaseType, tableName)} default values;",
                DatabaseType.MySql => $"insert into {QuoteQualifiedName(databaseType, tableName)} values ();",
                DatabaseType.SqLite => $"insert into {QuoteQualifiedName(databaseType, tableName)} default values;",
                _ => null
            };

            return defaultInsertSql is null
                ? null
                : new EditableResultSetCommand(defaultInsertSql, new Dictionary<string, object?>());
        }

        var parameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
        var quotedColumns = new List<string>();
        var parameterNames = new List<string>();

        for (var index = 0; index < columns.Count; index++)
        {
            var parameterName = $"p{index}";
            quotedColumns.Add(QuoteIdentifier(databaseType, columns[index].Name));
            parameterNames.Add(FormatParameterReference(databaseType, parameterName));
            parameters[parameterName] = columns[index].Value;
        }

        var sql = $"insert into {QuoteQualifiedName(databaseType, tableName)} ({string.Join(", ", quotedColumns)}) values ({string.Join(", ", parameterNames)});";
        return new EditableResultSetCommand(sql, parameters);
    }

    public static EditableResultSetCommand? BuildUpdate(
        DatabaseType databaseType,
        string tableName,
        IReadOnlyList<string> gridHeaders,
        IReadOnlyList<ColumnModel> tableColumns,
        IReadOnlyList<object?> originalValues,
        IReadOnlyList<object?> currentValues)
    {
        var primaryKeys = tableColumns.Where(column => column.IsPrimaryKey).Select(column => column.Name).ToList();
        if (primaryKeys.Count == 0)
            return null;

        var parameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
        var assignments = new List<string>();
        var parameterIndex = 0;

        for (var index = 0; index < gridHeaders.Count && index < currentValues.Count && index < originalValues.Count; index++)
        {
            var columnName = gridHeaders[index];
            if (primaryKeys.Contains(columnName, StringComparer.OrdinalIgnoreCase))
                continue;

            if (Equals(originalValues[index], currentValues[index]))
                continue;

            var parameterName = $"p{parameterIndex++}";
            assignments.Add($"{QuoteIdentifier(databaseType, columnName)} = {FormatParameterReference(databaseType, parameterName)}");
            parameters[parameterName] = currentValues[index];
        }

        if (assignments.Count == 0)
            return null;

        var where = BuildPrimaryKeyWhereClause(databaseType, gridHeaders, originalValues, primaryKeys, parameters, ref parameterIndex);
        var sql = $"update {QuoteQualifiedName(databaseType, tableName)} set {string.Join(", ", assignments)} where {where};";
        return new EditableResultSetCommand(sql, parameters);
    }

    public static EditableResultSetCommand? BuildDelete(
        DatabaseType databaseType,
        string tableName,
        IReadOnlyList<string> gridHeaders,
        IReadOnlyList<ColumnModel> tableColumns,
        IReadOnlyList<object?> originalValues)
    {
        var primaryKeys = tableColumns.Where(column => column.IsPrimaryKey).Select(column => column.Name).ToList();
        if (primaryKeys.Count == 0)
            return null;

        var parameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase);
        var parameterIndex = 0;
        var where = BuildPrimaryKeyWhereClause(databaseType, gridHeaders, originalValues, primaryKeys, parameters, ref parameterIndex);
        var sql = $"delete from {QuoteQualifiedName(databaseType, tableName)} where {where};";
        return new EditableResultSetCommand(sql, parameters);
    }

    private static string BuildPrimaryKeyWhereClause(
        DatabaseType databaseType,
        IReadOnlyList<string> gridHeaders,
        IReadOnlyList<object?> sourceValues,
        IReadOnlyList<string> primaryKeys,
        IDictionary<string, object?> parameters,
        ref int parameterIndex)
    {
        var predicates = new List<string>();
        foreach (var keyColumn in primaryKeys)
        {
            var index = FindColumnIndex(gridHeaders, keyColumn);
            if (index < 0)
                throw new InvalidOperationException($"Primary key column '{keyColumn}' is not present in the result grid.");

            var parameterName = $"p{parameterIndex++}";
            predicates.Add($"{QuoteIdentifier(databaseType, keyColumn)} = {FormatParameterReference(databaseType, parameterName)}");
            parameters[parameterName] = sourceValues[index];
        }

        return string.Join(" and ", predicates);
    }

    private static HashSet<string> GetPrimaryKeySet(IReadOnlyList<ColumnModel> tableColumns)
    {
        return tableColumns
            .Where(column => column.IsPrimaryKey)
            .Select(column => column.Name)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);
    }

    private static string QuoteQualifiedName(DatabaseType databaseType, string tableName)
    {
        var dialect = SqlDialect.For(databaseType);
        return string.Join(".", dialect.SplitQualifiedName(tableName).Select(part => QuoteIdentifier(databaseType, part)));
    }

    // Table and column names arrive as stored in the database (from the driver, the catalog or
    // resolved from the query text), so they are quoted exactly.
    private static string QuoteIdentifier(DatabaseType databaseType, string identifier)
    {
        return SqlDialect.For(databaseType).QuoteIdentifier(identifier);
    }

    private static string FormatParameterReference(DatabaseType databaseType, string parameterName)
    {
        return SqlDialect.For(databaseType).FormatParameterReference(parameterName);
    }

    private static int FindColumnIndex(IReadOnlyList<string> gridHeaders, string columnName)
    {
        for (var index = 0; index < gridHeaders.Count; index++)
        {
            if (string.Equals(gridHeaders[index], columnName, StringComparison.OrdinalIgnoreCase))
                return index;
        }

        return -1;
    }
}
