using DataDeveloper.Data.Enums;
using DataDeveloper.Data.Models;
using DataDeveloper.Data.Services;
using Xunit;

namespace DataDeveloper.Tests;

public class EditableResultSetCommandBuilderTests
{
    [Fact]
    public void BuildUpdate_UsesSqlServerQuotingAndPrimaryKeyWhereClause()
    {
        var command = EditableResultSetCommandBuilder.BuildUpdate(
            DatabaseType.SqlServer,
            "dbo.clientes",
            ["id", "nome"],
            [new ColumnModel { Name = "id", IsPrimaryKey = true }, new ColumnModel { Name = "nome" }],
            [1, "Alice"],
            [1, "Bob"]);

        Assert.NotNull(command);
        Assert.Equal("update [dbo].[clientes] set [nome] = @p0 where [id] = @p1;", command!.Sql);
        Assert.Equal("Bob", command.Parameters["p0"]);
        Assert.Equal(1, command.Parameters["p1"]);
    }

    [Fact]
    public void BuildInsert_OmitsNullPrimaryKeyForMySql()
    {
        var command = EditableResultSetCommandBuilder.BuildInsert(
            DatabaseType.MySql,
            "clientes",
            ["id", "nome"],
            [new ColumnModel { Name = "id", IsPrimaryKey = true }, new ColumnModel { Name = "nome" }],
            [null, "Alice"]);

        Assert.NotNull(command);
        Assert.Equal("insert into `clientes` (`nome`) values (@p0);", command!.Sql);
        Assert.Equal("Alice", command.Parameters["p0"]);
    }

    [Fact]
    public void BuildInsert_OmitsNullColumnsBackedByDefaults()
    {
        var command = EditableResultSetCommandBuilder.BuildInsert(
            DatabaseType.PostgresSql,
            "customers",
            ["customer_id", "name", "email", "created_at"],
            [
                new ColumnModel { Name = "customer_id", IsPrimaryKey = true, IsAutoGenerated = true },
                new ColumnModel { Name = "name" },
                new ColumnModel { Name = "email" },
                new ColumnModel { Name = "created_at", HasDefaultValue = true }
            ],
            [null, "Alice", "alice@example.com", null]);

        Assert.NotNull(command);
        Assert.Equal("insert into \"customers\" (\"name\", \"email\") values (@p0, @p1);", command!.Sql);
        Assert.Equal("Alice", command.Parameters["p0"]);
        Assert.Equal("alice@example.com", command.Parameters["p1"]);
    }

    [Fact]
    public void BuildInsert_PreservesExplicitNullForColumnsWithoutDefaults()
    {
        var command = EditableResultSetCommandBuilder.BuildInsert(
            DatabaseType.PostgresSql,
            "customers",
            ["customer_id", "name", "email"],
            [
                new ColumnModel { Name = "customer_id", IsPrimaryKey = true, IsAutoGenerated = true },
                new ColumnModel { Name = "name" },
                new ColumnModel { Name = "email", IsNullable = true }
            ],
            [null, "Alice", null]);

        Assert.NotNull(command);
        Assert.Equal("insert into \"customers\" (\"name\", \"email\") values (@p0, @p1);", command!.Sql);
        Assert.Equal("Alice", command.Parameters["p0"]);
        Assert.Null(command.Parameters["p1"]);
    }

    [Fact]
    public void BuildDelete_UsesMySqlQuotingAndPrimaryKeyWhereClause()
    {
        var command = EditableResultSetCommandBuilder.BuildDelete(
            DatabaseType.MySql,
            "clientes",
            ["id", "nome"],
            [new ColumnModel { Name = "id", IsPrimaryKey = true }, new ColumnModel { Name = "nome" }],
            [7, "Alice"]);

        Assert.NotNull(command);
        Assert.Equal("delete from `clientes` where `id` = @p0;", command!.Sql);
        Assert.Equal(7, command.Parameters["p0"]);
    }

    [Fact]
    public void BuildUpdate_UsesPostgresQuotingAndPrimaryKeyWhereClause()
    {
        var command = EditableResultSetCommandBuilder.BuildUpdate(
            DatabaseType.PostgresSql,
            "public.clientes",
            ["id", "nome"],
            [new ColumnModel { Name = "id", IsPrimaryKey = true }, new ColumnModel { Name = "nome" }],
            [1, "Alice"],
            [1, "Bob"]);

        Assert.NotNull(command);
        Assert.Equal("update \"public\".\"clientes\" set \"nome\" = @p0 where \"id\" = @p1;", command!.Sql);
        Assert.Equal("Bob", command.Parameters["p0"]);
        Assert.Equal(1, command.Parameters["p1"]);
    }

    [Fact]
    public void BuildInsert_UsesOracleQuotingAndParameterPrefix()
    {
        var command = EditableResultSetCommandBuilder.BuildInsert(
            DatabaseType.Oracle,
            "CLIENTES",
            ["ID", "NOME"],
            [new ColumnModel { Name = "ID", IsPrimaryKey = true }, new ColumnModel { Name = "NOME" }],
            [1, "Alice"]);

        Assert.NotNull(command);
        Assert.Equal("insert into \"CLIENTES\" (\"ID\", \"NOME\") values (:p0, :p1);", command!.Sql);
        Assert.Equal(1, command.Parameters["p0"]);
        Assert.Equal("Alice", command.Parameters["p1"]);
    }

    [Fact]
    public void BuildInsert_NormalizesOracleIdentifiersToUpperCase()
    {
        var command = EditableResultSetCommandBuilder.BuildInsert(
            DatabaseType.Oracle,
            "datadeveloper.customers",
            ["customer_id", "name"],
            [new ColumnModel { Name = "customer_id", IsPrimaryKey = true }, new ColumnModel { Name = "name" }],
            [1, "Alice"]);

        Assert.NotNull(command);
        Assert.Equal("insert into \"DATADEVELOPER\".\"CUSTOMERS\" (\"CUSTOMER_ID\", \"NAME\") values (:p0, :p1);", command!.Sql);
    }

    [Fact]
    public void BuildDelete_UsesSqLiteQuotingAndPrimaryKeyWhereClause()
    {
        var command = EditableResultSetCommandBuilder.BuildDelete(
            DatabaseType.SqLite,
            "clientes",
            ["id", "nome"],
            [new ColumnModel { Name = "id", IsPrimaryKey = true }, new ColumnModel { Name = "nome" }],
            [7, "Alice"]);

        Assert.NotNull(command);
        Assert.Equal("delete from \"clientes\" where \"id\" = @p0;", command!.Sql);
        Assert.Equal(7, command.Parameters["p0"]);
    }

    [Theory]
    [InlineData(DatabaseType.PostgresSql, "insert into \"clientes\" default values;")]
    [InlineData(DatabaseType.SqLite, "insert into \"clientes\" default values;")]
    public void BuildInsert_UsesDefaultValuesForSupportedProviders(DatabaseType databaseType, string expectedSql)
    {
        var command = EditableResultSetCommandBuilder.BuildInsert(
            databaseType,
            "clientes",
            ["id"],
            [new ColumnModel { Name = "id", IsPrimaryKey = true }],
            [null]);

        Assert.NotNull(command);
        Assert.Equal(expectedSql, command!.Sql);
        Assert.Empty(command.Parameters);
    }
}
