using System.Diagnostics;
using System.Reflection;
using DataDeveloper.Core;
using DataDeveloper.Data.Enums;
using DataDeveloper.Data.Interfaces;
using DataDeveloper.Data.Models;
using DataDeveloper.Enums;
using DataDeveloper.Interfaces;
using DataDeveloper.Models;
using DataDeveloper.Services;
using DataDeveloper.ViewModels;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace DataDeveloper.Tests;

public class TabDataGridViewModelTests
{
    [Fact]
    public void LoadedCleanRow_WithMissingRequiredValue_DoesNotShowValidationSummary()
    {
        var viewModel = CreateViewModel();
        SetEditableMetadata(viewModel);
        viewModel.GridHeaders.Add("id");
        viewModel.GridHeaders.Add("nome");
        viewModel.GridRows.Add(new EditableGridRow([1, null]));

        ValidateAllRows(viewModel);

        Assert.False(viewModel.ShowValidationSummary);
        Assert.Equal(0, viewModel.ValidationErrorCount);
    }

    [Fact]
    public void NewRow_WithMissingRequiredValue_ShowsValidationSummary()
    {
        var viewModel = CreateViewModel();
        SetEditableMetadata(viewModel);
        viewModel.GridHeaders.Add("id");
        viewModel.GridHeaders.Add("nome");
        viewModel.GridRows.Add(new EditableGridRow([null, null], isNew: true));

        ValidateAllRows(viewModel);

        Assert.True(viewModel.ShowValidationSummary);
        Assert.Equal(1, viewModel.ValidationErrorCount);
        Assert.Equal("1 required field pending", viewModel.ValidationSummary);
    }

    [Fact]
    public async Task RefreshDataAsync_ReusesStatementParameters()
    {
        var executor = new CapturingStatementExecutor();
        var services = new ServiceCollection();
        services.AddSingleton<IEventAggregatorService, EventAggregatorService>();
        services.AddSingleton<IDialogService, NoOpDialogService>();
        services.AddSingleton<AppDataFileService>();
        var serviceProvider = services.BuildServiceProvider();

        var parameters = new Dictionary<string, object?>(StringComparer.OrdinalIgnoreCase)
        {
            ["IntegrationId"] = Guid.Parse("c681c0c4-aa79-4aba-9b94-665f6f7ebcf7")
        };

        var viewModel = new TestTabDataGridViewModel(
            new ConnectionSettings
            {
                DatabaseType = DatabaseType.SqlServer,
                Name = "Test"
            },
            new StatementResult(
                dataReader: null,
                connection: null,
                command: null,
                statement: "select * from Integration where id = @IntegrationId",
                watcher: new Stopwatch(),
                parameters: parameters),
            selectedPage: 100,
            name: "result 01",
            canClose: true,
            serviceProvider: serviceProvider,
            messageTargetId: Guid.NewGuid(),
            statementExecutor: executor);

        var refreshMethod = typeof(TabDataGridViewModel).GetMethod("RefreshDataAsync", BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(refreshMethod);

        var refreshTask = Assert.IsAssignableFrom<Task>(refreshMethod!.Invoke(viewModel, null));
        await refreshTask;

        Assert.Equal("select * from Integration where id = @IntegrationId", executor.LastSql);
        Assert.NotNull(executor.LastParameters);
        Assert.Equal(parameters["IntegrationId"], executor.LastParameters!["IntegrationId"]);
    }

    private static TestTabDataGridViewModel CreateViewModel()
    {
        var services = new ServiceCollection();
        services.AddSingleton<IEventAggregatorService, EventAggregatorService>();
        services.AddSingleton<IDialogService, NoOpDialogService>();
        services.AddSingleton<AppDataFileService>();
        var serviceProvider = services.BuildServiceProvider();

        return new TestTabDataGridViewModel(
            new ConnectionSettings
            {
                DatabaseType = DatabaseType.MySql,
                Name = "NassServer"
            },
            new StatementResult(
                dataReader: null,
                connection: null,
                command: null,
                statement: "select * from clientes",
                watcher: new Stopwatch(),
                parameters: null),
            selectedPage: 100,
            name: "result 01",
            canClose: true,
            serviceProvider: serviceProvider,
            messageTargetId: Guid.NewGuid(),
            statementExecutor: new CapturingStatementExecutor());
    }

    private static void SetEditableMetadata(TabDataGridViewModel viewModel)
    {
        var metadata = new EditableResultSetMetadata(
            new ResultSetEditabilityInfo(true, "clientes", null),
            [
                new ColumnModel
                {
                    Name = "id",
                    IsPrimaryKey = true,
                    IsAutoGenerated = true
                },
                new ColumnModel
                {
                    Name = "nome",
                    IsNullable = false
                }
            ]);

        typeof(TabDataGridViewModel)
            .GetProperty(nameof(TabDataGridViewModel.EditableMetadata))!
            .SetValue(viewModel, metadata);
    }

    private static void ValidateAllRows(TabDataGridViewModel viewModel)
    {
        var validateMethod = typeof(TabDataGridViewModel)
            .GetMethod("ValidateAllRows", BindingFlags.Instance | BindingFlags.NonPublic);
        Assert.NotNull(validateMethod);
        validateMethod!.Invoke(viewModel, null);
    }

    private sealed class CapturingStatementExecutor : IStatementExecutor
    {
        public string? LastSql { get; private set; }
        public IReadOnlyDictionary<string, object?>? LastParameters { get; private set; }
        public bool HasActiveTransaction => false;

        public Task<IEnumerable<StatementResult>> ExecuteStatement(
            string sqlStatement,
            IReadOnlyDictionary<string, object?>? parameters = null,
            int? commandTimeoutSeconds = null,
            CancellationToken cancellationToken = default)
        {
            LastSql = sqlStatement;
            LastParameters = parameters;
            return Task.FromResult<IEnumerable<StatementResult>>([]);
        }

        public void Cancel()
        {
        }

        public Task BeginTransaction(CancellationToken cancellationToken = default)
        {
            return Task.CompletedTask;
        }

        public Task CommitTransaction(CancellationToken cancellationToken = default)
        {
            return Task.CompletedTask;
        }

        public Task<int> ExecuteCommandInTransaction(
            EditableResultSetCommand command,
            int? commandTimeoutSeconds = null,
            CancellationToken cancellationToken = default)
        {
            return Task.FromResult(0);
        }

        public Task RollbackTransaction(CancellationToken cancellationToken = default)
        {
            return Task.CompletedTask;
        }
    }

    private sealed class TestTabDataGridViewModel : TabDataGridViewModel
    {
        private readonly IStatementExecutor _statementExecutor;

        public TestTabDataGridViewModel(
            ConnectionSettings connectionSettings,
            StatementResult statementResult,
            int selectedPage,
            string name,
            bool canClose,
            IServiceProvider serviceProvider,
            Guid messageTargetId,
            IStatementExecutor statementExecutor)
            : base(connectionSettings, statementResult, selectedPage, name, canClose, serviceProvider, messageTargetId)
        {
            _statementExecutor = statementExecutor;
        }

        protected override IStatementExecutor CreateStatementExecutor()
        {
            return _statementExecutor;
        }
    }

    private sealed class NoOpDialogService : IDialogService
    {
        public Task<DialogResult> ShowDialogAsync(string message, string? title = null, DialogButtons buttons = DialogButtons.Ok, DialogIcon icon = DialogIcon.Info) => Task.FromResult(DialogResult.Cancel);
        public Task<DialogResult> ShowDialogResult(string message, string? title = null) => Task.FromResult(DialogResult.Cancel);
        public Task ShowMessageAsync(string message, string? title = null) => Task.CompletedTask;
        public Task ShowAboutAsync(string version, Func<Task> checkForUpdatesAsync) => Task.CompletedTask;
        public Task<DialogResult> ShowReleaseUpdateAsync(string message, string? title = null) => Task.FromResult(DialogResult.Cancel);
        public Task<string?> ShowSaveFileDialogAsync(string? suggestedName = null, string? title = null) => Task.FromResult<string?>(null);
        public Task<string?> ShowOpenFileAsync(string? title = null) => Task.FromResult<string?>(null);
        public Task<string?> ShowOpenDatabaseFileAsync(string? title = null) => Task.FromResult<string?>(null);
        public Task<string?> ShowCreateDatabaseFileAsync(string? suggestedName = null, string? title = null) => Task.FromResult<string?>(null);
        public Task<string?> ShowSaveJsonFileDialogAsync(string? suggestedName = null, string? title = null) => Task.FromResult<string?>(null);
        public Task<string?> ShowOpenJsonFileDialogAsync(string? title = null) => Task.FromResult<string?>(null);
        public Task<string?> ShowOpenImportFileAsync(string? title = null) => Task.FromResult<string?>(null);
        public Task<string?> ShowSaveExportFileDialogAsync(GridExportFormat format, string? suggestedName = null, string? title = null) => Task.FromResult<string?>(null);
    }
}
