using DataDeveloper.Data.Enums;
using DataDeveloper.Data.Models.TableDesigner;
using DataDeveloper.Data.Services.TableDesigner;
using Xunit;

namespace DataDeveloper.Tests;

public class TableDdlScriptBuilderTests
{
    [Fact]
    public void BuildCreateTableScript_GeneratesSqlServerTableWithConstraintsAndIndex()
    {
        var table = new TableDefinition
        {
            SchemaName = "dbo",
            TableName = "Orders"
        };
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "Id",
            DataType = "int",
            IsNullable = false,
            IsIdentity = true
        });
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "CustomerId",
            DataType = "int",
            IsNullable = false
        });
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "Code",
            DataType = "nvarchar",
            Length = 50,
            IsNullable = false,
            DefaultValue = "N''"
        });
        table.PrimaryKey.Name = "PK_Orders";
        table.PrimaryKey.ColumnNames.Add("Id");
        table.ForeignKeys.Add(new TableForeignKeyDefinition
        {
            Name = "FK_Orders_Customers",
            ReferencedSchemaName = "dbo",
            ReferencedTableName = "Customers",
            OnDeleteAction = "cascade",
            OnUpdateAction = "no action"
        });
        table.ForeignKeys[0].ColumnNames.Add("CustomerId");
        table.ForeignKeys[0].ReferencedColumnNames.Add("Id");
        table.Indexes.Add(new TableIndexDefinition
        {
            Name = "IX_Orders_CustomerId"
        });
        table.Indexes[0].Columns.Add(new TableIndexColumnDefinition { Name = "CustomerId" });

        var sql = TableDdlScriptBuilder.BuildCreateTableScript(DatabaseType.SqlServer, table);

        Assert.Equal(
            """
            create table [dbo].[Orders]
            (
                [Id] int identity(1, 1) not null,
                [CustomerId] int not null,
                [Code] nvarchar(50) not null default N'',
                constraint [PK_Orders] primary key ([Id]),
                constraint [FK_Orders_Customers]
                    foreign key ([CustomerId])
                    references [dbo].[Customers] ([Id])
                    on delete cascade on update no action
            );

            create index [IX_Orders_CustomerId]
                on [dbo].[Orders] ([CustomerId]);
            """,
            sql);
    }

    [Fact]
    public void BuildCreateTableScript_GeneratesPostgresTableWithSchemaAndIdentity()
    {
        var table = new TableDefinition
        {
            SchemaName = "public",
            TableName = "orders"
        };
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "id",
            DataType = "integer",
            IsNullable = false,
            IsIdentity = true
        });
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "code",
            DataType = "varchar",
            Length = 80,
            IsNullable = false
        });
        table.PrimaryKey.ColumnNames.Add("id");

        var sql = TableDdlScriptBuilder.BuildCreateTableScript(DatabaseType.PostgresSql, table);

        Assert.Equal(
            """
            create table "public"."orders"
            (
                "id" integer generated by default as identity not null,
                "code" varchar(80) not null,
                primary key ("id")
            );
            """,
            sql);
    }

    [Fact]
    public void BuildCreateTableScript_GeneratesMySqlTableWithForeignKeyAndIndex()
    {
        var table = new TableDefinition
        {
            TableName = "orders"
        };
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "id",
            DataType = "int",
            IsNullable = false,
            IsIdentity = true
        });
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "customer_id",
            DataType = "int",
            IsNullable = false
        });
        table.PrimaryKey.ColumnNames.Add("id");
        table.ForeignKeys.Add(new TableForeignKeyDefinition
        {
            Name = "fk_orders_customers",
            ReferencedTableName = "customers",
            OnDeleteAction = "cascade",
            OnUpdateAction = "restrict"
        });
        table.ForeignKeys[0].ColumnNames.Add("customer_id");
        table.ForeignKeys[0].ReferencedColumnNames.Add("id");
        table.Indexes.Add(new TableIndexDefinition
        {
            Name = "ix_orders_customer",
            IsUnique = true
        });
        table.Indexes[0].Columns.Add(new TableIndexColumnDefinition { Name = "customer_id" });

        var sql = TableDdlScriptBuilder.BuildCreateTableScript(DatabaseType.MySql, table);

        Assert.Equal(
            """
            create table `orders`
            (
                `id` int auto_increment not null,
                `customer_id` int not null,
                primary key (`id`),
                constraint `fk_orders_customers`
                    foreign key (`customer_id`)
                    references `customers` (`id`)
                    on delete cascade on update restrict
            ) engine=InnoDB;

            create unique index `ix_orders_customer`
                on `orders` (`customer_id`);
            """,
            sql);
    }

    [Fact]
    public void BuildCreateTableScript_GeneratesMySqlTableWithoutEngineWhenNoForeignKeyExists()
    {
        var table = new TableDefinition
        {
            TableName = "orders"
        };
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "id",
            DataType = "int",
            IsNullable = false,
            IsIdentity = true
        });
        table.PrimaryKey.ColumnNames.Add("id");

        var sql = TableDdlScriptBuilder.BuildCreateTableScript(DatabaseType.MySql, table);

        Assert.Equal(
            """
            create table `orders`
            (
                `id` int auto_increment not null,
                primary key (`id`)
            );
            """,
            sql);
    }

    [Fact]
    public void BuildCreateTableScript_GeneratesSqliteInlineAutoincrementPrimaryKey()
    {
        var table = new TableDefinition
        {
            SchemaName = "ignored",
            TableName = "orders"
        };
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "id",
            DataType = "integer",
            IsNullable = false,
            IsIdentity = true
        });
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "name",
            DataType = "text",
            IsNullable = true
        });
        table.PrimaryKey.ColumnNames.Add("id");

        var sql = TableDdlScriptBuilder.BuildCreateTableScript(DatabaseType.SqLite, table);

        Assert.Equal(
            """
            create table "orders"
            (
                "id" integer primary key autoincrement,
                "name" text null
            );
            """,
            sql);
    }

    [Fact]
    public void BuildCreateTableScript_GeneratesSqliteForeignKeyAndIndex()
    {
        var table = new TableDefinition
        {
            TableName = "orders"
        };
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "id",
            DataType = "integer",
            IsNullable = false
        });
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "customer_id",
            DataType = "integer",
            IsNullable = false
        });
        table.PrimaryKey.ColumnNames.Add("id");
        table.ForeignKeys.Add(new TableForeignKeyDefinition
        {
            Name = "fk_orders_customers",
            ReferencedTableName = "customers",
            OnDeleteAction = "cascade",
            OnUpdateAction = "no action"
        });
        table.ForeignKeys[0].ColumnNames.Add("customer_id");
        table.ForeignKeys[0].ReferencedColumnNames.Add("id");
        table.Indexes.Add(new TableIndexDefinition
        {
            Name = "ix_orders_customer"
        });
        table.Indexes[0].Columns.Add(new TableIndexColumnDefinition { Name = "customer_id", Descending = true });

        var sql = TableDdlScriptBuilder.BuildCreateTableScript(DatabaseType.SqLite, table);

        Assert.Equal(
            """
            create table "orders"
            (
                "id" integer not null,
                "customer_id" integer not null,
                primary key ("id"),
                constraint "fk_orders_customers"
                    foreign key ("customer_id")
                    references "customers" ("id")
                    on delete cascade on update no action
            );

            create index "ix_orders_customer"
                on "orders" ("customer_id" desc);
            """,
            sql);
    }

    [Fact]
    public void BuildCreateTableScript_GeneratesOracleForeignKeyWithoutOnUpdate()
    {
        var table = new TableDefinition
        {
            TableName = "ORDERS"
        };
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "ID",
            DataType = "number",
            Precision = 18,
            IsNullable = false,
            IsIdentity = true
        });
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "CUSTOMER_ID",
            DataType = "number",
            Precision = 18,
            IsNullable = false
        });
        table.PrimaryKey.ColumnNames.Add("ID");
        table.ForeignKeys.Add(new TableForeignKeyDefinition
        {
            Name = "FK_ORDERS_CUSTOMERS",
            ReferencedTableName = "CUSTOMERS",
            OnDeleteAction = "cascade",
            OnUpdateAction = "cascade"
        });
        table.ForeignKeys[0].ColumnNames.Add("CUSTOMER_ID");
        table.ForeignKeys[0].ReferencedColumnNames.Add("ID");

        var sql = TableDdlScriptBuilder.BuildCreateTableScript(DatabaseType.Oracle, table);

        Assert.Equal(
            """
            create table ORDERS
            (
                ID number(18) generated by default as identity not null,
                CUSTOMER_ID number(18) not null,
                primary key (ID),
                constraint FK_ORDERS_CUSTOMERS
                    foreign key (CUSTOMER_ID)
                    references CUSTOMERS (ID)
                    on delete cascade
            );
            """,
            sql);
    }

    [Fact]
    public void BuildCreateTableScript_NormalizesOracleRegularIdentifiersToUppercase()
    {
        var table = new TableDefinition
        {
            TableName = "NewTable_Order"
        };
        table.Columns.Add(new TableColumnDefinition
        {
            Name = "Id",
            DataType = "integer",
            IsNullable = false
        });
        table.PrimaryKey.ColumnNames.Add("Id");
        table.Indexes.Add(new TableIndexDefinition
        {
            Name = "IX_NewTable_Order_Id"
        });
        table.Indexes[0].Columns.Add(new TableIndexColumnDefinition { Name = "Id" });

        var sql = TableDdlScriptBuilder.BuildCreateTableScript(DatabaseType.Oracle, table);

        Assert.Equal(
            """
            create table NEWTABLE_ORDER
            (
                ID integer not null,
                primary key (ID)
            );

            create index IX_NEWTABLE_ORDER_ID
                on NEWTABLE_ORDER (ID);
            """,
            sql);
    }

    [Fact]
    public void BuildAlterTableScript_SqlServer_AddedColumn_GeneratesAddColumn()
    {
        var original = BuildBasicTable();
        var current = BuildBasicTable();
        current.Columns.Add(new TableColumnDefinition { Name = "Notes", DataType = "nvarchar", Length = 200, IsNullable = true });

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqlServer, original, current);

        Assert.Equal("alter table [dbo].[Orders] add [Notes] nvarchar(200) null;", sql);
    }

    [Fact]
    public void BuildAlterTableScript_SqlServer_DroppedColumn_GeneratesDropColumn()
    {
        var original = BuildBasicTable();
        original.Columns.Add(new TableColumnDefinition { Name = "Notes", DataType = "nvarchar", Length = 200, IsNullable = true });
        var current = BuildBasicTable();

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqlServer, original, current);

        Assert.Equal("alter table [dbo].[Orders] drop column [Notes];", sql);
    }

    [Fact]
    public void BuildAlterTableScript_MySql_AddedColumn_UsesAddColumnKeyword()
    {
        var original = BuildBasicTable(DatabaseType.MySql);
        var current = BuildBasicTable(DatabaseType.MySql);
        current.Columns.Add(new TableColumnDefinition { Name = "Notes", DataType = "varchar", Length = 200, IsNullable = true });

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.MySql, original, current);

        Assert.Equal("alter table `Orders` add column `Notes` varchar(200) null;", sql);
    }

    [Fact]
    public void BuildAlterTableScript_Oracle_AddedColumn_OmitsColumnKeyword()
    {
        var original = BuildBasicTable(DatabaseType.Oracle);
        var current = BuildBasicTable(DatabaseType.Oracle);
        current.Columns.Add(new TableColumnDefinition { Name = "NOTES", DataType = "varchar2", Length = 200, IsNullable = true });

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.Oracle, original, current);

        Assert.Equal("alter table ORDERS add NOTES varchar2(200) null;", sql);
    }

    [Fact]
    public void BuildAlterTableScript_AddedForeignKey_GeneratesAlterAddConstraint()
    {
        var original = BuildBasicTable();
        var current = BuildBasicTable();
        current.Columns.Add(new TableColumnDefinition { Name = "CustomerId", DataType = "int", IsNullable = false });
        current.ForeignKeys.Add(new TableForeignKeyDefinition
        {
            Name = "FK_Orders_Customers",
            ReferencedTableName = "Customers",
            OnDeleteAction = "cascade"
        });
        current.ForeignKeys[0].ColumnNames.Add("CustomerId");
        current.ForeignKeys[0].ReferencedColumnNames.Add("Id");

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqlServer, original, current);

        Assert.Contains("alter table [dbo].[Orders] add [CustomerId] int not null;", sql);
        Assert.Contains(
            """
            alter table [dbo].[Orders] add constraint [FK_Orders_Customers]
                    foreign key ([CustomerId])
                    references [Customers] ([Id])
                    on delete cascade;
            """,
            sql);
    }

    [Fact]
    public void BuildAlterTableScript_DroppedForeignKey_MySql_UsesDropForeignKeySyntax()
    {
        var original = BuildBasicTable(DatabaseType.MySql);
        original.Columns.Add(new TableColumnDefinition { Name = "CustomerId", DataType = "int", IsNullable = false });
        original.ForeignKeys.Add(new TableForeignKeyDefinition
        {
            Name = "FK_Orders_Customers",
            ReferencedTableName = "Customers"
        });
        original.ForeignKeys[0].ColumnNames.Add("CustomerId");
        original.ForeignKeys[0].ReferencedColumnNames.Add("Id");
        var current = BuildBasicTable(DatabaseType.MySql);
        current.Columns.Add(new TableColumnDefinition { Name = "CustomerId", DataType = "int", IsNullable = false });

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.MySql, original, current);

        Assert.Equal("alter table `Orders` drop foreign key `FK_Orders_Customers`;", sql);
    }

    [Fact]
    public void BuildAlterTableScript_AddedIndex_GeneratesCreateIndex()
    {
        var original = BuildBasicTable();
        var current = BuildBasicTable();
        current.Indexes.Add(new TableIndexDefinition { Name = "IX_Orders_Id" });
        current.Indexes[0].Columns.Add(new TableIndexColumnDefinition { Name = "Id" });

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqlServer, original, current);

        Assert.Equal(
            """
            create index [IX_Orders_Id]
                on [dbo].[Orders] ([Id]);
            """,
            sql);
    }

    [Fact]
    public void BuildAlterTableScript_DroppedIndex_SqlServer_UsesDropIndexOnTableSyntax()
    {
        var original = BuildBasicTable();
        original.Indexes.Add(new TableIndexDefinition { Name = "IX_Orders_Id" });
        original.Indexes[0].Columns.Add(new TableIndexColumnDefinition { Name = "Id" });
        var current = BuildBasicTable();

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqlServer, original, current);

        Assert.Equal("drop index [IX_Orders_Id] on [dbo].[Orders];", sql);
    }

    [Fact]
    public void BuildAlterTableScript_DroppedIndex_MySql_UsesAlterTableDropIndexSyntax()
    {
        var original = BuildBasicTable(DatabaseType.MySql);
        original.Indexes.Add(new TableIndexDefinition { Name = "IX_Orders_Id" });
        original.Indexes[0].Columns.Add(new TableIndexColumnDefinition { Name = "Id" });
        var current = BuildBasicTable(DatabaseType.MySql);

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.MySql, original, current);

        Assert.Equal("alter table `Orders` drop index `IX_Orders_Id`;", sql);
    }

    [Fact]
    public void BuildAlterTableScript_PrimaryKeyChanged_DropsAndAddsConstraint()
    {
        var original = BuildBasicTable();
        var current = BuildBasicTable();
        current.Columns.Add(new TableColumnDefinition { Name = "TenantId", DataType = "int", IsNullable = false });
        current.PrimaryKey.ColumnNames.Add("TenantId");

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqlServer, original, current);

        Assert.Contains("alter table [dbo].[Orders] drop constraint [PK_Orders];", sql);
        Assert.Contains("alter table [dbo].[Orders] add constraint [PK_Orders] primary key ([Id], [TenantId]);", sql);
    }

    [Fact]
    public void BuildAlterTableScript_SqLite_OnlyAdditions_EmitsLightweightAddColumn()
    {
        var original = BuildBasicTable(DatabaseType.SqLite);
        var current = BuildBasicTable(DatabaseType.SqLite);
        current.Columns.Add(new TableColumnDefinition { Name = "Notes", DataType = "text", IsNullable = true, OriginalName = null });

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqLite, original, current);

        Assert.Equal("alter table \"Orders\" add column \"Notes\" text null;", sql);
    }

    [Fact]
    public void BuildAlterTableScript_SqLite_IndexChange_TriggersFullRebuild()
    {
        var original = BuildBasicTable(DatabaseType.SqLite);
        original.Columns[0].OriginalName = original.Columns[0].Name;
        original.Indexes.Add(new TableIndexDefinition { Name = "IX_Orders_Id" });
        original.Indexes[0].Columns.Add(new TableIndexColumnDefinition { Name = "Id" });
        var current = BuildBasicTable(DatabaseType.SqLite);
        current.Columns[0].OriginalName = original.Columns[0].Name;
        // current drops the index without touching columns; SQLite has no DROP INDEX-only ALTER
        // shortcut in this builder's model, so any structural change triggers the full rebuild.

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqLite, original, current);

        Assert.Contains("pragma foreign_keys=off;", sql);
        Assert.Contains("create table \"temp_Orders\"", sql);
        Assert.Contains("insert into \"temp_Orders\" (\"Id\") select \"Id\" from \"Orders\";", sql);
        Assert.Contains("drop table \"Orders\";", sql);
        Assert.Contains("alter table \"temp_Orders\" rename to \"Orders\";", sql);
        Assert.Contains("pragma foreign_keys=on;", sql);
        Assert.DoesNotContain("create index \"IX_Orders_Id\"", sql);
    }

    [Fact]
    public void BuildAlterTableScript_SqLite_ColumnRename_TriggersRebuildWithColumnMapping()
    {
        var original = BuildBasicTable(DatabaseType.SqLite);
        original.Columns[0].OriginalName = original.Columns[0].Name;
        var current = BuildBasicTable(DatabaseType.SqLite);
        current.Columns[0].OriginalName = "Id";
        current.Columns[0].Name = "OrderId";
        current.PrimaryKey.ColumnNames.Clear();
        current.PrimaryKey.ColumnNames.Add("OrderId");

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqLite, original, current);

        Assert.Contains("insert into \"temp_Orders\" (\"OrderId\") select \"Id\" from \"Orders\";", sql);
    }

    [Theory]
    [InlineData(DatabaseType.SqlServer, "alter table [dbo].[Orders] alter column [Code] nvarchar(100) null;")]
    [InlineData(DatabaseType.PostgresSql, "alter table \"Orders\" alter column \"Code\" type varchar(100);\n\nalter table \"Orders\" alter column \"Code\" drop not null;")]
    [InlineData(DatabaseType.Oracle, "alter table ORDERS modify (CODE varchar2(100) null);")]
    public void BuildAlterTableScript_ColumnTypeAndNullableChange_GeneratesProviderAlter(DatabaseType databaseType, string expected)
    {
        var original = BuildTableWithCodeColumn(databaseType, length: 50, isNullable: false);
        var current = BuildTableWithCodeColumn(databaseType, length: 100, isNullable: true);
        current.Columns[1].OriginalName = original.Columns[1].Name;

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(databaseType, original, current);

        Assert.Equal(expected, sql);
    }

    [Fact]
    public void BuildAlterTableScript_MySql_ColumnChange_UsesModifyColumn()
    {
        var original = BuildTableWithCodeColumn(DatabaseType.MySql, length: 50, isNullable: false);
        var current = BuildTableWithCodeColumn(DatabaseType.MySql, length: 100, isNullable: true);
        current.Columns[1].OriginalName = original.Columns[1].Name;

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.MySql, original, current);

        Assert.Equal("alter table `Orders` modify column `Code` varchar(100) null;", sql);
    }

    [Fact]
    public void BuildAlterTableScript_SqlServer_ColumnRename_UsesSpRename()
    {
        var original = BuildTableWithCodeColumn(DatabaseType.SqlServer, length: 50, isNullable: false);
        var current = BuildTableWithCodeColumn(DatabaseType.SqlServer, length: 50, isNullable: false);
        current.Columns[1].OriginalName = original.Columns[1].Name;
        current.Columns[1].Name = "OrderCode";

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqlServer, original, current);

        Assert.Equal("exec sp_rename '[dbo].[Orders].Code', 'OrderCode', 'COLUMN';", sql);
    }

    [Fact]
    public void BuildAlterTableScript_MySql_ColumnRename_UsesChangeColumn()
    {
        var original = BuildTableWithCodeColumn(DatabaseType.MySql, length: 50, isNullable: false);
        var current = BuildTableWithCodeColumn(DatabaseType.MySql, length: 50, isNullable: false);
        current.Columns[1].OriginalName = original.Columns[1].Name;
        current.Columns[1].Name = "OrderCode";

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.MySql, original, current);

        Assert.Equal("alter table `Orders` change column `Code` `OrderCode` varchar(50) not null;", sql);
    }

    [Fact]
    public void BuildAlterTableScript_PostgreSql_ColumnRename_UsesRenameColumn()
    {
        var original = BuildTableWithCodeColumn(DatabaseType.PostgresSql, length: 50, isNullable: false);
        var current = BuildTableWithCodeColumn(DatabaseType.PostgresSql, length: 50, isNullable: false);
        current.Columns[1].OriginalName = original.Columns[1].Name;
        current.Columns[1].Name = "order_code";

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.PostgresSql, original, current);

        Assert.Equal("alter table \"Orders\" rename column \"Code\" to \"order_code\";", sql);
    }

    [Theory]
    [InlineData(DatabaseType.SqlServer, "exec sp_rename '[dbo].[Orders]', 'Purchases';")]
    [InlineData(DatabaseType.MySql, "alter table `Orders` rename to `Purchases`;")]
    [InlineData(DatabaseType.PostgresSql, "alter table \"Orders\" rename to \"Purchases\";")]
    [InlineData(DatabaseType.Oracle, "alter table ORDERS rename to PURCHASES;")]
    public void BuildAlterTableScript_TableRename_GeneratesProviderStatement(DatabaseType databaseType, string expected)
    {
        var original = BuildBasicTable(databaseType);
        original.Columns[0].OriginalName = original.Columns[0].Name;
        var current = BuildBasicTable(databaseType);
        current.Columns[0].OriginalName = original.Columns[0].Name;
        current.TableName = databaseType == DatabaseType.Oracle ? "PURCHASES" : "Purchases";

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(databaseType, original, current);

        Assert.Equal(expected, sql);
    }

    [Fact]
    public void BuildAlterTableScript_SqlServer_DefaultValueChange_DropsOldConstraintAndAddsNew()
    {
        var original = BuildTableWithCodeColumn(DatabaseType.SqlServer, length: 50, isNullable: true);
        original.Columns[1].DefaultValue = "N''";
        original.Columns[1].ProviderOptions["default_constraint_name"] = "DF_Orders_Code";

        var current = BuildTableWithCodeColumn(DatabaseType.SqlServer, length: 50, isNullable: true);
        current.Columns[1].OriginalName = original.Columns[1].Name;
        current.Columns[1].DefaultValue = "N'n/a'";

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqlServer, original, current);

        Assert.Equal(
            "alter table [dbo].[Orders] drop constraint [DF_Orders_Code];\n\nalter table [dbo].[Orders] add default N'n/a' for [Code];",
            sql);
    }

    [Fact]
    public void BuildIndexDefinition_SqlServer_ClusteredAndFillFactor_AreRendered()
    {
        var original = BuildBasicTable();
        original.Columns[0].OriginalName = original.Columns[0].Name;
        var current = BuildBasicTable();
        current.Columns[0].OriginalName = original.Columns[0].Name;
        var index = new TableIndexDefinition { Name = "IX_Orders_Id" };
        index.Columns.Add(new TableIndexColumnDefinition { Name = "Id" });
        index.ProviderOptions["clustered"] = "true";
        index.ProviderOptions["fillfactor"] = "90";
        current.Indexes.Add(index);

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqlServer, original, current);

        Assert.Equal(
            "create clustered index [IX_Orders_Id]\n    on [dbo].[Orders] ([Id]) with (fillfactor = 90);",
            sql);
    }

    [Fact]
    public void BuildIndexDefinition_Postgres_UsingAndWhere_AreRendered()
    {
        var original = BuildBasicTable(DatabaseType.PostgresSql);
        original.Columns[0].OriginalName = original.Columns[0].Name;
        var current = BuildBasicTable(DatabaseType.PostgresSql);
        current.Columns[0].OriginalName = original.Columns[0].Name;
        var index = new TableIndexDefinition { Name = "IX_Orders_Id" };
        index.Columns.Add(new TableIndexColumnDefinition { Name = "Id" });
        index.ProviderOptions["using"] = "hash";
        index.ProviderOptions["where"] = "\"Id\" > 0";
        current.Indexes.Add(index);

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.PostgresSql, original, current);

        Assert.Equal(
            "create index \"IX_Orders_Id\"\n    on \"Orders\" using hash (\"Id\") where \"Id\" > 0;",
            sql);
    }

    [Fact]
    public void BuildIndexDefinition_MySql_PrefixLength_IsRendered()
    {
        var original = BuildBasicTable(DatabaseType.MySql);
        original.Columns[0].OriginalName = original.Columns[0].Name;
        var current = BuildBasicTable(DatabaseType.MySql);
        current.Columns[0].OriginalName = original.Columns[0].Name;
        var index = new TableIndexDefinition { Name = "IX_Orders_Id" };
        var indexColumn = new TableIndexColumnDefinition { Name = "Id" };
        indexColumn.ProviderOptions["prefix_length"] = "10";
        index.Columns.Add(indexColumn);
        current.Indexes.Add(index);

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.MySql, original, current);

        Assert.Equal(
            "create index `IX_Orders_Id`\n    on `Orders` (`Id`(10));",
            sql);
    }

    [Fact]
    public void BuildAlterTableScript_UneditedDecimalColumn_WithSpuriousLoadedLength_GeneratesNoStatements()
    {
        // Regression test: some providers report a non-zero internal storage size for a
        // column's "Length" even when the type has no length concept at all (for example SQL
        // Server's sys.columns.max_length is non-zero for decimal columns) — that value used to
        // be compared directly against "current" (always null for a type that doesn't support
        // Length), making every untouched decimal/datetime2/uniqueidentifier/etc. column look
        // like it had been retyped as soon as the edit-table designer opened.
        var original = BuildBasicTable();
        original.Columns[0].OriginalName = original.Columns[0].Name;
        original.Columns.Add(new TableColumnDefinition
        {
            OriginalName = "Total",
            Name = "Total",
            DataType = "decimal",
            Precision = 18,
            Scale = 2,
            Length = 9, // spurious storage-size value a loader could report for this type
            IsNullable = false
        });

        var current = BuildBasicTable();
        current.Columns[0].OriginalName = original.Columns[0].Name;
        current.Columns.Add(new TableColumnDefinition
        {
            OriginalName = "Total",
            Name = "Total",
            DataType = "decimal",
            Precision = 18,
            Scale = 2,
            Length = null,
            IsNullable = false
        });

        var sql = TableDdlScriptBuilder.BuildAlterTableScript(DatabaseType.SqlServer, original, current);

        Assert.Equal(string.Empty, sql);
    }

    private static TableDefinition BuildTableWithCodeColumn(DatabaseType databaseType, int length, bool isNullable)
    {
        var table = BuildBasicTable(databaseType);
        table.Columns.Add(new TableColumnDefinition
        {
            Name = databaseType == DatabaseType.Oracle ? "CODE" : "Code",
            DataType = databaseType == DatabaseType.Oracle ? "varchar2" : databaseType == DatabaseType.SqlServer ? "nvarchar" : "varchar",
            Length = length,
            IsNullable = isNullable
        });
        return table;
    }

    private static TableDefinition BuildBasicTable(DatabaseType databaseType = DatabaseType.SqlServer)
    {
        var table = new TableDefinition
        {
            SchemaName = databaseType == DatabaseType.SqlServer ? "dbo" : string.Empty,
            TableName = databaseType == DatabaseType.Oracle ? "ORDERS" : "Orders"
        };
        table.Columns.Add(new TableColumnDefinition
        {
            Name = databaseType == DatabaseType.Oracle ? "ID" : "Id",
            DataType = databaseType == DatabaseType.Oracle ? "number" : "int",
            IsNullable = false,
            IsIdentity = true
        });
        table.PrimaryKey.Name = databaseType == DatabaseType.Oracle ? "PK_ORDERS" : "PK_Orders";
        table.PrimaryKey.ColumnNames.Add(databaseType == DatabaseType.Oracle ? "ID" : "Id");
        return table;
    }
}
