<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
        <PackageReference Include="ExcelDataReader" Version="3.9.0" />
        <PackageReference Include="Fody" Version="6.9.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
        <PackageReference Include="Dapper" Version="2.1.72" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.4" />
        <PackageReference Include="MySqlConnector" Version="2.4.0" />
        <PackageReference Include="Npgsql" Version="8.0.3" />
        <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.8.0" />
        <PackageReference Include="System.Text.Encoding.CodePages" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DataDeveloper.Core\DataDeveloper.Core.csproj" />
        <ProjectReference Include="..\DataDeveloper.Antlr\DataDeveloper.Antlr.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Providers\" />
    </ItemGroup>

</Project>
