using System.Data.Common;
using System.Text;
using DataDeveloper.Data.Services;
using MySqlConnector;

namespace DataDeveloper.Data.Providers.MySql;

public class MySqlDatabaseProvider : DatabaseProviderBase<MySqlConnectionSettings>
{
    public MySqlDatabaseProvider(MySqlConnectionSettings connectionSettings)
        : base(connectionSettings)
    {
    }

    public override DbConnection GetConnection()
    {
        var sslMode = ConnectionSettings.Encrypt
            ? ConnectionSettings.TrustServerCertificate
                ? MySqlSslMode.Required
                : MySqlSslMode.VerifyCA
            : MySqlSslMode.None;

        var connectionStringBuilder = new MySqlConnectionStringBuilder
        {
            Server = ConnectionSettings.Server,
            Database = ConnectionSettings.Database,
            UserID = ConnectionSettings.User,
            Password = ConnectionSettings.Password,
            Port = ConnectionSettings.Port,
            SslMode = sslMode,
            AllowPublicKeyRetrieval = true
        };

        return new MySqlConnection(connectionStringBuilder.ConnectionString);
    }

    public override IReadOnlyList<string> GetAvailableDatabaseNames()
    {
        using var connection = new MySqlConnection(BuildConnectionString(string.Empty));
        connection.Open();
        using var command = connection.CreateCommand();
        command.CommandText = """
                              show databases;
                              """;
        using var reader = command.ExecuteReader();
        var names = new List<string>();
        while (reader.Read())
            names.Add(reader.GetString(0));
        return names;
    }

    public override string GetTableStatement()
    {
        return """
               select table_name as name
               from information_schema.tables
               where table_schema = database()
                 and table_type = 'BASE TABLE'
               order by table_name;
               """;
    }

    public override string GetViewStatement()
    {
        return """
               select table_name as name
               from information_schema.views
               where table_schema = database()
               order by table_name;
               """;
    }

    public override string GetColumnStatement()
    {
        var sb = new StringBuilder();

        sb.AppendLine("select");
        sb.AppendLine("    c.column_name as `Name`,");
        sb.AppendLine("    c.data_type as `DataType`,");
        sb.AppendLine("    c.character_maximum_length as `Length`,");
        sb.AppendLine("    c.numeric_precision as `Precision`,");
        sb.AppendLine("    c.numeric_scale as `Scale`,");
        sb.AppendLine("    case when c.is_nullable = 'YES' then 1 else 0 end as `IsNullable`,");
        sb.AppendLine("    case when k.column_name is not null then 1 else 0 end as `IsPrimaryKey`,");
        sb.AppendLine("    case when c.extra like '%auto_increment%' then 1 else 0 end as `IsAutoGenerated`,");
        sb.AppendLine("    case when c.column_default is not null then 1 else 0 end as `HasDefaultValue`");
        sb.AppendLine("from information_schema.columns c");
        sb.AppendLine("left join information_schema.key_column_usage k");
        sb.AppendLine("    on k.table_schema = c.table_schema");
        sb.AppendLine("   and k.table_name = c.table_name");
        sb.AppendLine("   and k.column_name = c.column_name");
        sb.AppendLine("   and k.constraint_name = 'PRIMARY'");
        sb.AppendLine("where c.table_schema = database()");
        sb.AppendLine("  and c.table_name = @TableName");
        sb.AppendLine("order by c.ordinal_position;");

        return sb.ToString();
    }

    public override string GetProcedureStatement()
    {
        return """
               select
                   routine_name as Name,
                   specific_name as SpecificName
               from information_schema.routines
               where routine_schema = database()
                 and routine_type = 'PROCEDURE'
               order by routine_name;
               """;
    }

    public override string GetFunctionStatement()
    {
        return """
               select
                   routine_name as Name,
                   specific_name as SpecificName,
                   data_type as DataType
               from information_schema.routines
               where routine_schema = database()
                 and routine_type = 'FUNCTION'
               order by routine_name;
               """;
    }

    public override string GetRoutineParameterStatement()
    {
        return """
               select
                   coalesce(parameter_name, 'return') as Name,
                   data_type as DataType,
                   coalesce(character_maximum_length, 0) as Length,
                   coalesce(numeric_precision, 0) as `Precision`,
                   coalesce(numeric_scale, 0) as `Scale`,
                   cast(1 as unsigned) as `IsNullable`,
                   parameter_mode as `Mode`,
                   ordinal_position as `Position`
               from information_schema.parameters
               where specific_schema = database()
                 and specific_name = @SpecificName
               order by ordinal_position;
               """;
    }

    public override string GetColumnDefaultValueStatement()
    {
        return """
               select
                   column_name as ColumnName,
                   column_default as DefaultValueExpression
               from information_schema.columns
               where table_schema = database()
                 and table_name = @TableName
               order by ordinal_position;
               """;
    }

    public override string GetPrimaryKeyStatement()
    {
        return """
               select
                   k.constraint_name as ConstraintName,
                   k.column_name as ColumnName,
                   k.ordinal_position as OrdinalPosition
               from information_schema.key_column_usage k
               where k.table_schema = database()
                 and k.table_name = @TableName
                 and k.constraint_name = 'PRIMARY'
               order by k.ordinal_position;
               """;
    }

    public override string GetForeignKeyStatement()
    {
        return """
               select
                   k.constraint_name as ConstraintName,
                   k.column_name as ColumnName,
                   k.ordinal_position as OrdinalPosition,
                   k.referenced_table_schema as ReferencedSchemaName,
                   k.referenced_table_name as ReferencedTableName,
                   k.referenced_column_name as ReferencedColumnName,
                   lower(rc.delete_rule) as OnDeleteAction,
                   lower(rc.update_rule) as OnUpdateAction
               from information_schema.key_column_usage k
               join information_schema.referential_constraints rc
                   on rc.constraint_schema = k.table_schema
                  and rc.constraint_name = k.constraint_name
               where k.table_schema = database()
                 and k.table_name = @TableName
                 and k.referenced_table_name is not null
               order by k.constraint_name, k.ordinal_position;
               """;
    }

    public override string GetIndexStatement()
    {
        return """
               select
                   index_name as IndexName,
                   case when non_unique = 0 then 1 else 0 end as IsUnique,
                   column_name as ColumnName,
                   case when collation = 'D' then 1 else 0 end as IsDescending,
                   seq_in_index as OrdinalPosition,
                   sub_part as PrefixLength
               from information_schema.statistics
               where table_schema = database()
                 and table_name = @TableName
                 and index_name <> 'PRIMARY'
               order by index_name, seq_in_index;
               """;
    }

    private string BuildConnectionString(string? databaseName)
    {
        var sslMode = ConnectionSettings.Encrypt
            ? ConnectionSettings.TrustServerCertificate
                ? MySqlSslMode.Required
                : MySqlSslMode.VerifyCA
            : MySqlSslMode.None;

        var connectionStringBuilder = new MySqlConnectionStringBuilder
        {
            Server = ConnectionSettings.Server,
            Database = databaseName,
            UserID = ConnectionSettings.User,
            Password = ConnectionSettings.Password,
            Port = ConnectionSettings.Port,
            SslMode = sslMode,
            AllowPublicKeyRetrieval = true
        };

        return connectionStringBuilder.ConnectionString;
    }
}
